/**
 * indicatorRegistry.ts
 *
 * 트레이더가 가장 많이 보는 지표 100개 카탈로그.
 *
 * 출처: CryptoQuant Most Viewed, Glassnode, Messari, Dune Analytics,
 *       DefiLlama, Coinglass, X(트위터) 인플루언서 언급 빈도 분석
 *       (2026-04-25 기준)
 *
 * displayType:
 *   'chart_pane'    — ChartBoard sub-pane (현재 엔진 지원)
 *   'chart_overlay' — 메인 차트 오버레이 (현재 엔진 지원)
 *   'engine'        — 엔진이 계산해서 오른쪽 HUD / Evidence에 표시
 *   'external'      — 외부 플랫폼 딥링크 (즉시 열기)
 *
 * tier:
 *   'A' — 엔진/차트에서 이미 지원
 *   'B' — 백엔드 확장으로 지원 가능
 *   'C' — 외부 플랫폼 링크
 */

export type IndicatorCategory =
  | 'onchain'
  | 'derivatives'
  | 'defi'
  | 'technical'
  | 'sentiment'
  | 'macro';

export type DisplayType = 'chart_pane' | 'chart_overlay' | 'engine' | 'external';
export type Tier = 'A' | 'B' | 'C';

export interface IndicatorDef {
  id: string;
  name: string;
  shortName: string;
  category: IndicatorCategory;
  subcategory: string;
  sources: string[];         // ['CryptoQuant', 'Glassnode', ...]
  description: string;
  why: string;               // 한 줄: 왜 트레이더가 보나
  displayType: DisplayType;
  tier: Tier;
  engineKey?: string;        // chartIndicators IndicatorKey (Tier A만)
  externalUrl?: string;
  externalLabel?: string;
  tags: string[];
  popularity: number;        // 1–5 (5 = 가장 많이 봄)
  signal?: {
    bullish: string;
    bearish: string;
  };
}

export const INDICATOR_REGISTRY: IndicatorDef[] = [

  // ─────────────────────────────────────────────────────────────────────────
  // CATEGORY: ON-CHAIN
  // ─────────────────────────────────────────────────────────────────────────

  {
    id: 'exchange_reserve',
    name: 'Exchange Reserve',
    shortName: 'EX Reserve',
    category: 'onchain',
    subcategory: 'exchange_flow',
    sources: ['CryptoQuant'],
    description: '거래소가 보유한 BTC/ETH 총량',
    why: '감소 = 인출(축적). 증가 = 매도 준비. 가장 직관적인 매도 압력 지표.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://cryptoquant.com/asset/btc/chart/exchange-flows/exchange-reserve',
    externalLabel: 'CryptoQuant',
    tags: ['exchange', 'flow', 'reserve', 'selling pressure', 'withdrawal'],
    popularity: 5,
    signal: {
      bullish: 'Reserve 지속 감소 (인출 증가)',
      bearish: 'Reserve 급증 (거래소 입금)',
    },
  },
  {
    id: 'exchange_netflow',
    name: 'Exchange Netflow',
    shortName: 'Netflow',
    category: 'onchain',
    subcategory: 'exchange_flow',
    sources: ['CryptoQuant'],
    description: '거래소 순유입/유출 (Inflow - Outflow)',
    why: '음수 = 인출 > 입금 → 축적 신호. 양수 = 매도 압력.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://cryptoquant.com/asset/btc/chart/exchange-flows/netflow',
    externalLabel: 'CryptoQuant',
    tags: ['exchange', 'netflow', 'inflow', 'outflow', 'accumulation'],
    popularity: 5,
    signal: {
      bullish: '대규모 순유출 (−$3B 이상)',
      bearish: '연속 순유입 (매도 준비)',
    },
  },
  {
    id: 'mvrv_zscore',
    name: 'MVRV Z-Score',
    shortName: 'MVRV-Z',
    category: 'onchain',
    subcategory: 'market_cycle',
    sources: ['CryptoQuant', 'Glassnode'],
    description: '시장가치 vs 실현가치 표준편차. 과열/저평가 판단 최강 지표.',
    why: 'Z-Score > 7 = 역사적 천장. Z-Score < 0 = 역사적 바닥. 인플루언서 80% 매일 체크.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://cryptoquant.com/asset/btc/chart/market-data/mvrv-zscore',
    externalLabel: 'CryptoQuant',
    tags: ['mvrv', 'zscore', 'cycle', 'realized', 'market_value', 'overheated'],
    popularity: 5,
    signal: {
      bullish: 'Z-Score < 1 (축적 구간)',
      bearish: 'Z-Score > 7 (역사적 과열)',
    },
  },
  {
    id: 'nupl',
    name: 'NUPL (Net Unrealized Profit/Loss)',
    shortName: 'NUPL',
    category: 'onchain',
    subcategory: 'market_cycle',
    sources: ['CryptoQuant', 'Glassnode'],
    description: '전체 투자자의 미실현 수익/손실 비율',
    why: '투자자 감정·사이클 단계 판단. Euphoria(고점) vs Capitulation(바닥) 구분.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://cryptoquant.com/asset/btc/chart/market-data/nupl',
    externalLabel: 'CryptoQuant',
    tags: ['nupl', 'unrealized', 'profit', 'loss', 'capitulation', 'euphoria'],
    popularity: 5,
    signal: {
      bullish: 'NUPL < 0 (손실 구간 = 바닥 근처)',
      bearish: 'NUPL > 0.75 (과도한 수익 = 분배 구간)',
    },
  },
  {
    id: 'sopr',
    name: 'SOPR (Spent Output Profit Ratio)',
    shortName: 'SOPR',
    category: 'onchain',
    subcategory: 'holder_behavior',
    sources: ['CryptoQuant', 'Glassnode'],
    description: '이동된 코인의 매도 시점 손익 비율',
    why: 'SOPR > 1 = 수익 실현. SOPR < 1 = 손실 매도. 1.0 지지 = 강세 신호.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://cryptoquant.com/asset/btc/chart/on-chain-data/spent-output-profit-ratio',
    externalLabel: 'CryptoQuant',
    tags: ['sopr', 'profit', 'realized', 'spent', 'output', 'holder'],
    popularity: 5,
    signal: {
      bullish: 'SOPR 1.0 지지 반등',
      bearish: 'SOPR 1.0 하회 후 저항',
    },
  },
  {
    id: 'lth_sopr',
    name: 'LTH-SOPR (Long-Term Holder)',
    shortName: 'LTH-SOPR',
    category: 'onchain',
    subcategory: 'holder_behavior',
    sources: ['Glassnode'],
    description: '장기 홀더(155일 이상) 매도 수익 비율',
    why: 'LTH-SOPR 급등 = 장기 홀더 대규모 수익 실현 → 사이클 천장 신호.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://studio.glassnode.com/metrics?a=BTC&m=indicators.Sopr155',
    externalLabel: 'Glassnode',
    tags: ['lth', 'sopr', 'long-term', 'holder', 'profit'],
    popularity: 4,
    signal: {
      bullish: 'LTH-SOPR 1.0 이하 (장기 홀더 손실 매도 = 바닥)',
      bearish: 'LTH-SOPR 급등 (장기 홀더 수익 청산)',
    },
  },
  {
    id: 'active_addresses',
    name: 'Active Addresses',
    shortName: 'Active Addr',
    category: 'onchain',
    subcategory: 'network_activity',
    sources: ['CryptoQuant', 'Glassnode', 'Messari'],
    description: '하루 최소 1회 이상 거래한 고유 주소 수',
    why: '네트워크 실사용 선행 지표. X 인플루언서들이 가장 자주 인용하는 온체인 지표.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://cryptoquant.com/asset/btc/chart/network-data/active-addresses',
    externalLabel: 'CryptoQuant',
    tags: ['active', 'addresses', 'network', 'activity', 'users', 'adoption'],
    popularity: 5,
    signal: {
      bullish: '활성 주소 지속 증가 (모멘텀 강화)',
      bearish: '활성 주소 급감 (관심 이탈)',
    },
  },
  {
    id: 'realized_price',
    name: 'Realized Price',
    shortName: 'Realized $',
    category: 'onchain',
    subcategory: 'market_cycle',
    sources: ['Glassnode', 'CryptoQuant'],
    description: '모든 BTC가 마지막으로 이동한 가격의 평균',
    why: '장기 지지/저항 레벨. 가격이 이 선을 자석처럼 끌어당김. @KongBTC 등 인용.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://studio.glassnode.com/metrics?a=BTC&m=market.PriceRealizedUsd',
    externalLabel: 'Glassnode',
    tags: ['realized', 'price', 'cost_basis', 'support', 'resistance'],
    popularity: 5,
    signal: {
      bullish: '현재가 > Realized Price (수익 구간)',
      bearish: '현재가 < Realized Price (손실 구간)',
    },
  },
  {
    id: 'sth_cost_basis',
    name: 'STH Cost Basis (Short-Term Holder)',
    shortName: 'STH Basis',
    category: 'onchain',
    subcategory: 'holder_behavior',
    sources: ['Glassnode'],
    description: '155일 미만 보유자의 평균 취득 단가',
    why: '단기 트레이더 손익 기준. @glassnode가 매일 올리는 핵심 모델.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://studio.glassnode.com/metrics?a=BTC&m=indicators.ShortTermHolderCostBasis',
    externalLabel: 'Glassnode',
    tags: ['sth', 'cost_basis', 'short_term', 'holder', 'realized'],
    popularity: 4,
    signal: {
      bullish: '현재가 > STH Basis (단기 홀더 수익 구간)',
      bearish: '현재가 < STH Basis (단기 홀더 손실 → 매도 압력)',
    },
  },
  {
    id: 'coinbase_premium',
    name: 'Coinbase Premium Index',
    shortName: 'CB Premium',
    category: 'onchain',
    subcategory: 'exchange_flow',
    sources: ['CryptoQuant'],
    description: 'Coinbase BTC 가격 - Binance BTC 가격 스프레드',
    why: '양수 = 미국 기관 매수 압력. 음수 = 아시아/리테일 주도.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://cryptoquant.com/asset/btc/chart/market-data/coinbase-premium-index',
    externalLabel: 'CryptoQuant',
    tags: ['coinbase', 'premium', 'institutional', 'us', 'gap'],
    popularity: 4,
    signal: {
      bullish: 'Premium 지속 양수 (기관 매수)',
      bearish: 'Premium 음수 전환 (기관 철수)',
    },
  },
  {
    id: 'whale_ratio',
    name: 'Exchange Whale Ratio',
    shortName: 'Whale Ratio',
    category: 'onchain',
    subcategory: 'exchange_flow',
    sources: ['CryptoQuant'],
    description: '상위 10대 거래소 입금량 / 전체 입금량 비율',
    why: '0.85 이상 = 고래 대규모 입금 → 매도 압력 강화.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://cryptoquant.com/asset/btc/chart/exchange-flows/whale-ratio',
    externalLabel: 'CryptoQuant',
    tags: ['whale', 'ratio', 'large', 'inflow', 'exchange'],
    popularity: 4,
    signal: {
      bullish: 'Whale Ratio < 0.6 (고래 이탈)',
      bearish: 'Whale Ratio > 0.85 (고래 대규모 입금)',
    },
  },
  {
    id: 'miner_outflow',
    name: 'Miner Outflow',
    shortName: 'Miner Out',
    category: 'onchain',
    subcategory: 'miner',
    sources: ['CryptoQuant'],
    description: '채굴자 지갑에서 거래소로 이동한 BTC 량',
    why: '채굴자 매도 압력 선행 지표. 반감기 전후 핵심 체크.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://cryptoquant.com/asset/btc/chart/miner-flows/miner-outflow',
    externalLabel: 'CryptoQuant',
    tags: ['miner', 'outflow', 'selling', 'halving', 'revenue'],
    popularity: 4,
    signal: {
      bullish: 'Miner Outflow 감소 (채굴자 보유)',
      bearish: 'Miner Outflow 급증 (채굴자 매도)',
    },
  },
  {
    id: 'ssr',
    name: 'Stablecoin Supply Ratio (SSR)',
    shortName: 'SSR',
    category: 'onchain',
    subcategory: 'stablecoin',
    sources: ['CryptoQuant'],
    description: 'BTC 시총 / 스테이블코인 시총 비율',
    why: '낮을수록 스테이블코인 구매력 강함 = 잠재 매수력 높음.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://cryptoquant.com/asset/btc/chart/market-data/stablecoin-supply-ratio',
    externalLabel: 'CryptoQuant',
    tags: ['ssr', 'stablecoin', 'supply', 'ratio', 'buying_power'],
    popularity: 4,
    signal: {
      bullish: 'SSR 낮음 = 높은 구매력 (저평가)',
      bearish: 'SSR 높음 = 낮은 구매력',
    },
  },
  {
    id: 'nvt_ratio',
    name: 'NVT Ratio (Network Value to Transactions)',
    shortName: 'NVT',
    category: 'onchain',
    subcategory: 'market_cycle',
    sources: ['CryptoQuant', 'Glassnode'],
    description: '시가총액 / 온체인 거래량. "블록체인 P/E ratio"',
    why: '높은 NVT = 네트워크 과대평가. 낮은 NVT = 실사용 대비 저평가.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://cryptoquant.com/asset/btc/chart/network-data/nvt-ratio',
    externalLabel: 'CryptoQuant',
    tags: ['nvt', 'network', 'value', 'transactions', 'pe', 'ratio'],
    popularity: 3,
  },
  {
    id: 'hodl_waves',
    name: 'HODL Waves',
    shortName: 'HODL Waves',
    category: 'onchain',
    subcategory: 'holder_behavior',
    sources: ['Glassnode'],
    description: '보유 기간별 BTC 분포 (1d / 1w / 1m / 3m / 6m / 1y+)',
    why: '장기 홀더 비율 증가 = 공급 감소 = 강세 기반. Glassnode 핵심 시각화.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://studio.glassnode.com/metrics?a=BTC&m=supply.HodlWaves',
    externalLabel: 'Glassnode',
    tags: ['hodl', 'waves', 'long_term', 'holder', 'distribution', 'age'],
    popularity: 4,
  },
  {
    id: 'accumulation_trend_score',
    name: 'Accumulation Trend Score',
    shortName: 'Accum Score',
    category: 'onchain',
    subcategory: 'holder_behavior',
    sources: ['Glassnode'],
    description: '지갑 크기별 축적 강도 점수 (0~1)',
    why: '0.9 이상 = 전반적 축적. 0.1 이하 = 전반적 분배. 고래 동향 확인.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://studio.glassnode.com/metrics?a=BTC&m=distribution.AccumulationTrendScore',
    externalLabel: 'Glassnode',
    tags: ['accumulation', 'trend', 'score', 'whale', 'distribution'],
    popularity: 4,
    signal: {
      bullish: 'ATS > 0.8 (강한 축적)',
      bearish: 'ATS < 0.2 (강한 분배)',
    },
  },
  {
    id: 'supply_in_profit',
    name: 'Percent Supply in Profit',
    shortName: '% in Profit',
    category: 'onchain',
    subcategory: 'market_cycle',
    sources: ['Glassnode'],
    description: '현재가보다 낮은 가격에 취득한 코인 비율',
    why: '95% 이상 = 역사적 과열. 50% 이하 = 매도 압력 극대화 근처.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://studio.glassnode.com/metrics?a=BTC&m=supply.ProfitPercent',
    externalLabel: 'Glassnode',
    tags: ['supply', 'profit', 'percent', 'unrealized', 'cycle'],
    popularity: 4,
  },
  {
    id: 'realized_pl',
    name: 'Realized Profit/Loss Ratio',
    shortName: 'R P/L',
    category: 'onchain',
    subcategory: 'holder_behavior',
    sources: ['Glassnode'],
    description: '실현 수익 / 실현 손실 비율',
    why: '급락 후 이 비율이 올라오면 회복 신호. 장기 투자자 분석에 필수.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://studio.glassnode.com/metrics?a=BTC&m=indicators.RealizedProfitLossRatio',
    externalLabel: 'Glassnode',
    tags: ['realized', 'profit', 'loss', 'ratio'],
    popularity: 4,
  },
  {
    id: 'exchange_inflow',
    name: 'Exchange Inflow',
    shortName: 'EX Inflow',
    category: 'onchain',
    subcategory: 'exchange_flow',
    sources: ['CryptoQuant'],
    description: '거래소로 입금된 BTC 량',
    why: '대량 입금 = 매도 준비. 특히 고래 단일 거래 모니터링.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://cryptoquant.com/asset/btc/chart/exchange-flows/exchange-inflow',
    externalLabel: 'CryptoQuant',
    tags: ['exchange', 'inflow', 'deposit', 'selling', 'whale'],
    popularity: 4,
  },
  {
    id: 'exchange_outflow',
    name: 'Exchange Outflow',
    shortName: 'EX Outflow',
    category: 'onchain',
    subcategory: 'exchange_flow',
    sources: ['CryptoQuant'],
    description: '거래소에서 인출된 BTC 량',
    why: '대량 인출 = 장기 보유 목적 축적.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://cryptoquant.com/asset/btc/chart/exchange-flows/exchange-outflow',
    externalLabel: 'CryptoQuant',
    tags: ['exchange', 'outflow', 'withdrawal', 'accumulation', 'holding'],
    popularity: 4,
  },

  // ─────────────────────────────────────────────────────────────────────────
  // CATEGORY: DERIVATIVES
  // ─────────────────────────────────────────────────────────────────────────

  {
    id: 'funding_rate',
    name: 'Funding Rate',
    shortName: 'Funding',
    category: 'derivatives',
    subcategory: 'perpetual',
    sources: ['CryptoQuant', 'Coinglass'],
    description: '무기한 선물 자금 조달 비율 (롱/숏 균형)',
    why: '음수 전환 = 숏 스퀴즈 가능성. 극단적 양수 = 롱 청산 위험.',
    displayType: 'chart_pane',
    tier: 'A',
    engineKey: 'derivatives',
    externalUrl: 'https://coinglass.com/FundingRate',
    externalLabel: 'Coinglass',
    tags: ['funding', 'rate', 'perpetual', 'long', 'short', 'squeeze'],
    popularity: 5,
    signal: {
      bullish: 'Funding 음수 전환 (숏 스퀴즈 대기)',
      bearish: 'Funding 극단적 양수 (롱 과열)',
    },
  },
  {
    id: 'open_interest',
    name: 'Open Interest',
    shortName: 'OI',
    category: 'derivatives',
    subcategory: 'perpetual',
    sources: ['CryptoQuant', 'Coinglass'],
    description: '미결제 선물 계약 총량',
    why: 'OI 상승 + 가격 상승 = 강한 강세. OI 상승 + 가격 하락 = 숏 집중.',
    displayType: 'chart_pane',
    tier: 'A',
    engineKey: 'oi',
    externalUrl: 'https://coinglass.com/OpenInterest',
    externalLabel: 'Coinglass',
    tags: ['open_interest', 'oi', 'futures', 'leverage', 'contracts'],
    popularity: 5,
    signal: {
      bullish: 'OI 증가 + 가격 상승 (추세 강화)',
      bearish: 'OI 급증 + 가격 하락 (숏 과열)',
    },
  },
  {
    id: 'long_short_ratio',
    name: 'Long/Short Ratio',
    shortName: 'L/S Ratio',
    category: 'derivatives',
    subcategory: 'perpetual',
    sources: ['Coinglass', 'CryptoQuant'],
    description: '거래소별 롱/숏 포지션 비율',
    why: '>3 이면 극단적 롱 과열 → 반전 가능성. 인플루언서들이 단기 타이밍에 활용.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://coinglass.com/LongShortRatio',
    externalLabel: 'Coinglass',
    tags: ['long', 'short', 'ratio', 'sentiment', 'positioning'],
    popularity: 4,
    signal: {
      bullish: 'L/S < 0.8 (숏 과열 → 반등 가능)',
      bearish: 'L/S > 2.5 (롱 과열 → 조정 가능)',
    },
  },
  {
    id: 'liquidation_heatmap',
    name: 'Liquidation Heatmap',
    shortName: 'Liq Map',
    category: 'derivatives',
    subcategory: 'liquidation',
    sources: ['Coinglass'],
    description: '가격대별 청산 예상 규모 히트맵',
    why: '고밀도 구간 = 가격 magnet. 트레이더들이 손절 집중 구간 파악에 필수.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://coinglass.com/LiquidationData',
    externalLabel: 'Coinglass',
    tags: ['liquidation', 'heatmap', 'stop', 'squeeze', 'magnet'],
    popularity: 5,
  },
  {
    id: 'cvd',
    name: 'CVD (Cumulative Volume Delta)',
    shortName: 'CVD',
    category: 'derivatives',
    subcategory: 'volume',
    sources: ['Engine'],
    description: '누적 매수 체결 - 매도 체결 합산',
    why: 'CVD 하락 + 가격 상승 = 악성 다이버전스 (하락 예고). 엔진 직접 계산.',
    displayType: 'chart_pane',
    tier: 'A',
    engineKey: 'cvd',
    tags: ['cvd', 'delta', 'cumulative', 'volume', 'divergence'],
    popularity: 5,
    signal: {
      bullish: 'CVD 상승 전환 (매수세 우위)',
      bearish: 'CVD-가격 다이버전스 (거짓 상승)',
    },
  },
  {
    id: 'perps_volume',
    name: 'Perps Volume',
    shortName: 'Perps Vol',
    category: 'derivatives',
    subcategory: 'volume',
    sources: ['DefiLlama', 'Coinglass'],
    description: '무기한 선물 총 거래량',
    why: 'Spot vs Perps Volume 비율로 레버리지 투기 수준 파악.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://defillama.com/derivatives',
    externalLabel: 'DefiLlama',
    tags: ['perps', 'perpetual', 'volume', 'futures', 'leverage'],
    popularity: 3,
  },
  {
    id: 'basis_spread',
    name: 'Futures Basis / Contango',
    shortName: 'Basis',
    category: 'derivatives',
    subcategory: 'futures',
    sources: ['Coinglass'],
    description: '선물가 - 현물가 스프레드 (Basis)',
    why: '높은 Basis = 강한 기대감. 음수 = Backwardation (공황).',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://coinglass.com/Futures',
    externalLabel: 'Coinglass',
    tags: ['basis', 'contango', 'backwardation', 'futures', 'premium'],
    popularity: 3,
  },
  {
    id: 'oi_btc',
    name: 'OI Change (BTC Terms)',
    shortName: 'OI Δ BTC',
    category: 'derivatives',
    subcategory: 'perpetual',
    sources: ['CryptoQuant'],
    description: 'BTC 기준 OI 변화량 (USD 아닌 코인 수)',
    why: 'USD OI는 가격에 따라 변동되므로, BTC 기준 OI가 진짜 레버리지 변화 반영.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://cryptoquant.com/asset/btc/chart/derivatives/open-interest',
    externalLabel: 'CryptoQuant',
    tags: ['oi', 'open_interest', 'btc', 'terms', 'leverage'],
    popularity: 4,
  },

  // ─────────────────────────────────────────────────────────────────────────
  // CATEGORY: DEFI / DEX
  // ─────────────────────────────────────────────────────────────────────────

  {
    id: 'tvl',
    name: 'TVL (Total Value Locked)',
    shortName: 'TVL',
    category: 'defi',
    subcategory: 'liquidity',
    sources: ['DefiLlama', 'Messari', 'Dune'],
    description: 'DeFi 프로토콜에 잠긴 총 자산 가치',
    why: '채택도 + 유동성의 핵심 지표. Uniswap $220M TVL 이동 같은 이벤트 즉각 반영.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://defillama.com/',
    externalLabel: 'DefiLlama',
    tags: ['tvl', 'total_value_locked', 'liquidity', 'defi', 'protocol'],
    popularity: 5,
    signal: {
      bullish: 'TVL 급증 (새 자본 유입)',
      bearish: 'TVL 급감 (자본 이탈)',
    },
  },
  {
    id: 'dex_volume',
    name: 'DEX Volume',
    shortName: 'DEX Vol',
    category: 'defi',
    subcategory: 'trading',
    sources: ['DefiLlama', 'Dune'],
    description: '탈중앙화 거래소 24h 스왑 총 거래량',
    why: '실제 거래 활동량. 현재 전체 DEX 24h Volume ≈ $7.4B.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://defillama.com/dexs',
    externalLabel: 'DefiLlama',
    tags: ['dex', 'volume', 'swap', 'trading', 'uniswap', 'raydium'],
    popularity: 5,
  },
  {
    id: 'unique_swappers',
    name: 'Unique Swappers',
    shortName: 'Unique Swp',
    category: 'defi',
    subcategory: 'users',
    sources: ['Dune'],
    description: '기간 내 최소 1회 이상 스왑한 고유 지갑 수',
    why: 'Wash trading 걸러내는 핵심. 하루 2만 이상 = 실사용 DEX로 인정.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://dune.com/dex_metrics',
    externalLabel: 'Dune Analytics',
    tags: ['unique', 'swappers', 'users', 'dex', 'wash_trading', 'real'],
    popularity: 4,
  },
  {
    id: 'volume_tvl_ratio',
    name: 'Volume/TVL Ratio',
    shortName: 'Vol/TVL',
    category: 'defi',
    subcategory: 'efficiency',
    sources: ['DefiLlama', 'Dune'],
    description: '거래량 / TVL = DEX 자본 효율성',
    why: '높을수록 잠긴 자금 대비 활발한 거래. DEX 건강도 핵심 지표.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://defillama.com/dexs',
    externalLabel: 'DefiLlama',
    tags: ['volume', 'tvl', 'ratio', 'efficiency', 'capital', 'dex'],
    popularity: 4,
  },
  {
    id: 'fees_generated',
    name: 'Protocol Fees / Revenue',
    shortName: 'Fees',
    category: 'defi',
    subcategory: 'revenue',
    sources: ['DefiLlama', 'Token Terminal', 'Messari'],
    description: '프로토콜 + LP 수수료 수익 총합',
    why: '지속 가능성 판단. Fees/Revenue로 P/S Ratio 계산 가능.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://defillama.com/fees',
    externalLabel: 'DefiLlama',
    tags: ['fees', 'revenue', 'protocol', 'lp', 'sustainability', 'ps_ratio'],
    popularity: 4,
  },
  {
    id: 'top_token_pairs',
    name: 'Top Token Pairs',
    shortName: 'Top Pairs',
    category: 'defi',
    subcategory: 'trading',
    sources: ['Dune', 'DefiLlama'],
    description: '거래량 기준 상위 토큰 쌍',
    why: '어떤 토큰이 실제로 가장 많이 거래되는지 = 트렌드 선행 지표.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://dune.com/',
    externalLabel: 'Dune Analytics',
    tags: ['top', 'pairs', 'token', 'volume', 'trending', 'dex'],
    popularity: 3,
  },
  {
    id: 'dex_market_share',
    name: 'DEX Market Share',
    shortName: 'DEX Share',
    category: 'defi',
    subcategory: 'competition',
    sources: ['DefiLlama', 'Dune'],
    description: 'Uniswap / PancakeSwap / Raydium 등 DEX별 점유율',
    why: '지배적 DEX 변화 = 생태계 트렌드 신호.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://defillama.com/dexs',
    externalLabel: 'DefiLlama',
    tags: ['dex', 'market', 'share', 'uniswap', 'raydium', 'competition'],
    popularity: 3,
  },
  {
    id: 'token_unlocks',
    name: 'Token Unlocks / Vesting',
    shortName: 'Unlocks',
    category: 'defi',
    subcategory: 'supply',
    sources: ['Messari', 'Token Unlocks'],
    description: '예정된 토큰 잠금 해제 일정 및 규모',
    why: '대규모 unlock 직전 = 매도 압력 급증. 절대 놓치면 안 되는 이벤트.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://token.unlocks.app/',
    externalLabel: 'Token Unlocks',
    tags: ['token', 'unlock', 'vesting', 'supply', 'inflation', 'sell_pressure'],
    popularity: 4,
  },
  {
    id: 'bridge_volume',
    name: 'Bridge Volume',
    shortName: 'Bridge Vol',
    category: 'defi',
    subcategory: 'cross_chain',
    sources: ['DefiLlama'],
    description: '크로스체인 브릿지 총 이동 자산 규모',
    why: '특정 체인으로의 자본 이동 방향성 파악.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://defillama.com/bridges',
    externalLabel: 'DefiLlama',
    tags: ['bridge', 'cross_chain', 'volume', 'layer2', 'capital_flow'],
    popularity: 3,
  },
  {
    id: 'stablecoin_mcap',
    name: 'Stablecoin Market Cap',
    shortName: 'Stable Mcap',
    category: 'defi',
    subcategory: 'stablecoin',
    sources: ['DefiLlama'],
    description: '전체 스테이블코인 시가총액 합산',
    why: '증가 = 시장 진입 대기 자금 증가 (잠재 매수력). 감소 = 자본 이탈.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://defillama.com/stablecoins',
    externalLabel: 'DefiLlama',
    tags: ['stablecoin', 'market_cap', 'usdt', 'usdc', 'buying_power'],
    popularity: 4,
  },

  // ─────────────────────────────────────────────────────────────────────────
  // CATEGORY: TECHNICAL
  // ─────────────────────────────────────────────────────────────────────────

  {
    id: 'rsi',
    name: 'RSI (Relative Strength Index)',
    shortName: 'RSI',
    category: 'technical',
    subcategory: 'momentum',
    sources: ['Engine', 'TradingView'],
    description: '14봉 기준 과매수(>70) / 과매도(<30) 모멘텀 지표',
    why: '가장 기본적이고 가장 많이 보는 TA 지표. 다이버전스 분석에도 필수.',
    displayType: 'chart_pane',
    tier: 'A',
    engineKey: 'rsi',
    tags: ['rsi', 'momentum', 'overbought', 'oversold', 'divergence'],
    popularity: 5,
    signal: {
      bullish: 'RSI < 30 (과매도 반등 구간)',
      bearish: 'RSI > 70 (과매수 조정 구간)',
    },
  },
  {
    id: 'ema',
    name: 'EMA (Exponential Moving Average)',
    shortName: 'EMA',
    category: 'technical',
    subcategory: 'trend',
    sources: ['Engine'],
    description: '20/50/200 EMA. 트렌드 방향과 지지/저항 레벨',
    why: 'EMA200 = 장기 추세 판단 기준. EMA50/200 교차 = Golden/Death Cross.',
    displayType: 'chart_overlay',
    tier: 'A',
    engineKey: 'ema',
    tags: ['ema', 'moving_average', 'trend', 'golden_cross', 'death_cross', '200'],
    popularity: 5,
    signal: {
      bullish: '가격 > EMA200 (장기 강세)',
      bearish: '가격 < EMA200 (장기 약세)',
    },
  },
  {
    id: 'macd',
    name: 'MACD',
    shortName: 'MACD',
    category: 'technical',
    subcategory: 'momentum',
    sources: ['Engine'],
    description: 'MACD Line, Signal Line, Histogram 조합',
    why: '추세 전환 조기 감지. 히스토그램 다이버전스가 가장 강력한 신호.',
    displayType: 'chart_pane',
    tier: 'A',
    engineKey: 'macd',
    tags: ['macd', 'momentum', 'trend', 'signal', 'histogram', 'divergence'],
    popularity: 5,
    signal: {
      bullish: 'MACD > Signal Line (상향 교차)',
      bearish: 'MACD < Signal Line (하향 교차)',
    },
  },
  {
    id: 'bollinger_bands',
    name: 'Bollinger Bands',
    shortName: 'BB',
    category: 'technical',
    subcategory: 'volatility',
    sources: ['Engine'],
    description: '20MA ± 2σ. 변동성 채널.',
    why: 'Band Squeeze = 변동성 폭발 전조. Band Walk = 강한 추세.',
    displayType: 'chart_overlay',
    tier: 'A',
    engineKey: 'bb',
    tags: ['bollinger', 'bands', 'volatility', 'squeeze', 'band_walk'],
    popularity: 5,
  },
  {
    id: 'vwap',
    name: 'VWAP (Volume-Weighted Average Price)',
    shortName: 'VWAP',
    category: 'technical',
    subcategory: 'price',
    sources: ['Engine'],
    description: '거래량 가중 평균 가격. 기관 진입 기준선.',
    why: '기관이 VWAP 기준으로 주문 집행. VWAP 회복 = 강한 재매입 신호.',
    displayType: 'chart_overlay',
    tier: 'A',
    engineKey: 'vwap',
    tags: ['vwap', 'volume', 'weighted', 'institutional', 'benchmark'],
    popularity: 4,
    signal: {
      bullish: '가격 > VWAP (기관 매수 구간)',
      bearish: '가격 < VWAP (기관 매도 압력)',
    },
  },
  {
    id: 'volume',
    name: 'Volume',
    shortName: 'Volume',
    category: 'technical',
    subcategory: 'volume',
    sources: ['Engine'],
    description: '봉당 거래량 (Spot + Perp 합산)',
    why: '가격 움직임의 신뢰도 검증. 고거래량 돌파 = 진짜 브레이크아웃.',
    displayType: 'chart_pane',
    tier: 'A',
    engineKey: 'volume',
    tags: ['volume', 'bars', 'confirmation', 'breakout'],
    popularity: 5,
  },
  {
    id: 'atr',
    name: 'ATR (Average True Range)',
    shortName: 'ATR',
    category: 'technical',
    subcategory: 'volatility',
    sources: ['Engine'],
    description: '평균 실제 범위. 변동성 크기 측정.',
    why: 'Stop Loss 설정 기준. ATR×1.5 = 적정 손절 거리.',
    displayType: 'chart_overlay',
    tier: 'A',
    engineKey: 'atr_bands',
    tags: ['atr', 'volatility', 'stop_loss', 'range', 'true_range'],
    popularity: 4,
  },
  {
    id: 'obv',
    name: 'OBV (On-Balance Volume)',
    shortName: 'OBV',
    category: 'technical',
    subcategory: 'volume',
    sources: ['TradingView'],
    description: '누적 거래량 지표. 가격-OBV 다이버전스 탐지.',
    why: '숨겨진 매집/분산을 조기 감지. 가격보다 OBV가 먼저 신호.',
    displayType: 'chart_pane',
    tier: 'A',
    engineKey: 'obv',
    tags: ['obv', 'on_balance', 'volume', 'divergence', 'accumulation'],
    popularity: 3,
    signal: {
      bullish: '가격 하락 + OBV 상승 (강세 다이버전스)',
      bearish: '가격 상승 + OBV 하락 (약세 다이버전스)',
    },
  },
  {
    id: 'volume_profile',
    name: 'Volume Profile',
    shortName: 'Vol Profile',
    category: 'technical',
    subcategory: 'volume',
    sources: ['TradingView'],
    description: '가격대별 거래량 분포 (POC, Value Area)',
    why: 'POC = 가격이 돌아오는 자석. Value Area = 지지/저항 범위.',
    displayType: 'chart_overlay',
    tier: 'A',
    engineKey: 'volumeProfile',
    tags: ['volume', 'profile', 'poc', 'value_area', 'support', 'resistance'],
    popularity: 4,
    signal: {
      bullish: '가격이 POC 위 → 지지 확인',
      bearish: '가격이 POC 아래 → 저항 확인',
    },
  },
  {
    id: 'stochastic_rsi',
    name: 'Stochastic RSI',
    shortName: 'Stoch RSI',
    category: 'technical',
    subcategory: 'momentum',
    sources: ['TradingView'],
    description: 'RSI에 Stochastic 적용. 과매수/과매도 민감도 향상.',
    why: 'RSI보다 빠른 신호. 단기 진입 타이밍에 활용.',
    displayType: 'external',
    tier: 'B',
    externalUrl: 'https://www.tradingview.com/',
    externalLabel: 'TradingView',
    tags: ['stochastic', 'rsi', 'stoch', 'momentum', 'overbought', 'oversold'],
    popularity: 3,
  },
  {
    id: 'supertrend',
    name: 'Supertrend',
    shortName: 'Supertrend',
    category: 'technical',
    subcategory: 'trend',
    sources: ['TradingView'],
    description: 'ATR 기반 추세 추종 지표',
    why: '2025~2026년 트렌드. 강한 추세에서 신호가 명확. X에서 언급 급증.',
    displayType: 'external',
    tier: 'B',
    externalUrl: 'https://www.tradingview.com/',
    externalLabel: 'TradingView',
    tags: ['supertrend', 'trend', 'atr', 'following', 'signal'],
    popularity: 3,
  },
  {
    id: 'ichimoku',
    name: 'Ichimoku Cloud',
    shortName: 'Ichimoku',
    category: 'technical',
    subcategory: 'trend',
    sources: ['TradingView'],
    description: '일목균형표. Cloud, Kijun, Tenkan 복합 시스템.',
    why: 'Cloud 위 = 강세 구조. Kijun 지지 = 추세 지속 확인.',
    displayType: 'external',
    tier: 'B',
    externalUrl: 'https://www.tradingview.com/',
    externalLabel: 'TradingView',
    tags: ['ichimoku', 'cloud', 'kijun', 'tenkan', 'japanese', 'trend'],
    popularity: 3,
  },
  {
    id: 'fibonacci',
    name: 'Fibonacci Retracement',
    shortName: 'Fibonacci',
    category: 'technical',
    subcategory: 'price_levels',
    sources: ['TradingView'],
    description: '주요 고/저점 기준 0.236 / 0.382 / 0.5 / 0.618 / 0.786 레벨',
    why: '가장 많이 사용하는 지지/저항 레벨. 0.618 = "황금비율" 반등 지점.',
    displayType: 'external',
    tier: 'B',
    externalUrl: 'https://www.tradingview.com/',
    externalLabel: 'TradingView',
    tags: ['fibonacci', 'retracement', 'fib', '618', 'support', 'resistance'],
    popularity: 4,
  },

  // ─────────────────────────────────────────────────────────────────────────
  // CATEGORY: SENTIMENT
  // ─────────────────────────────────────────────────────────────────────────

  {
    id: 'fear_greed',
    name: 'Fear & Greed Index',
    shortName: 'F&G',
    category: 'sentiment',
    subcategory: 'market_sentiment',
    sources: ['Alternative.me', 'CNN'],
    description: '0~100 시장 감정 지수. 0=극단적 공포, 100=극단적 탐욕.',
    why: '극단 값에서 역발상 전략. 90+ = 매도 고려. 10- = 매수 고려.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://alternative.me/crypto/fear-and-greed-index/',
    externalLabel: 'Alternative.me',
    tags: ['fear', 'greed', 'sentiment', 'index', 'contrarian'],
    popularity: 5,
    signal: {
      bullish: 'F&G < 20 (극단적 공포 = 역발상 매수)',
      bearish: 'F&G > 85 (극단적 탐욕 = 역발상 매도)',
    },
  },
  {
    id: 'social_volume',
    name: 'Social Volume / Mention Velocity',
    shortName: 'Social Vol',
    category: 'sentiment',
    subcategory: 'social',
    sources: ['Santiment', 'LunarCrush'],
    description: '특정 코인 소셜 미디어 언급 빈도 증가율',
    why: '언급 급증 선행 → 가격 선행 신호. @AltCryptoGems 등 인플루언서 필수 체크.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://app.santiment.net/',
    externalLabel: 'Santiment',
    tags: ['social', 'volume', 'mention', 'velocity', 'trending', 'sentiment'],
    popularity: 3,
  },
  {
    id: 'etf_inflows',
    name: 'Bitcoin ETF Inflows',
    shortName: 'ETF Flows',
    category: 'sentiment',
    subcategory: 'institutional',
    sources: ['Farside Investors', 'CryptoQuant'],
    description: '미국 BTC 현물 ETF 순유입/유출 (BlackRock IBIT 등)',
    why: '기관 자금 이동 직접 추적. ETF 대규모 유입 = 가격 상방 압력.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://farside.co.uk/bitcoin-etf-flow-all-data/',
    externalLabel: 'Farside',
    tags: ['etf', 'inflow', 'outflow', 'blackrock', 'institutional', 'bitcoin'],
    popularity: 5,
    signal: {
      bullish: 'ETF 연속 순유입 (기관 매수)',
      bearish: 'ETF 대규모 유출 (기관 철수)',
    },
  },
  {
    id: 'google_trends',
    name: 'Google Trends',
    shortName: 'G Trends',
    category: 'sentiment',
    subcategory: 'social',
    sources: ['Google Trends'],
    description: '"Bitcoin" 검색량 추이',
    why: '리테일 관심도 척도. 검색량 급증 = 리테일 FOMO 진입 = 천장 신호.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://trends.google.com/trends/explore?q=bitcoin',
    externalLabel: 'Google Trends',
    tags: ['google', 'trends', 'search', 'fomo', 'retail', 'interest'],
    popularity: 3,
  },
  {
    id: 'pi_cycle_top',
    name: 'Pi Cycle Top Indicator',
    shortName: 'Pi Cycle',
    category: 'sentiment',
    subcategory: 'market_cycle',
    sources: ['LookIntoBitcoin'],
    description: '111DMA와 350DMA×2 교차 시 역사적 천장 신호',
    why: '과거 3번의 BTC 천장을 정확히 맞춘 지표. 한번 교차하면 즉시 매도.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://lookintobitcoin.com/charts/pi-cycle-top-indicator/',
    externalLabel: 'LookIntoBitcoin',
    tags: ['pi_cycle', 'top', 'ema', '111', '350', 'cycle', 'peak'],
    popularity: 3,
  },

  // ─────────────────────────────────────────────────────────────────────────
  // CATEGORY: MACRO
  // ─────────────────────────────────────────────────────────────────────────

  {
    id: 'global_m2',
    name: 'Global M2 Money Supply',
    shortName: 'Global M2',
    category: 'macro',
    subcategory: 'monetary',
    sources: ['TradingView', 'FRED'],
    description: '주요국 통화량 합산. BTC와 강한 상관관계.',
    why: 'M2 팽창 = BTC 상승. M2 수축 = BTC 하락. 사이클 판단에 필수.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://fred.stlouisfed.org/series/M2SL',
    externalLabel: 'FRED',
    tags: ['m2', 'money_supply', 'global', 'macro', 'liquidity', 'monetary'],
    popularity: 4,
  },
  {
    id: 'dxy',
    name: 'DXY (US Dollar Index)',
    shortName: 'DXY',
    category: 'macro',
    subcategory: 'fx',
    sources: ['TradingView'],
    description: '미 달러화 강세 지수. BTC와 역상관관계.',
    why: 'DXY 하락 = 위험자산 선호 = BTC 상승. DXY 상승 = BTC 약세.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://www.tradingview.com/symbols/TVC-DXY/',
    externalLabel: 'TradingView',
    tags: ['dxy', 'dollar', 'index', 'macro', 'risk_on', 'correlation'],
    popularity: 4,
    signal: {
      bullish: 'DXY 하락 추세 (위험자산 선호)',
      bearish: 'DXY 상승 추세 (달러 강세)',
    },
  },
  {
    id: 'us_10y_yield',
    name: 'US 10Y Treasury Yield',
    shortName: '10Y Yield',
    category: 'macro',
    subcategory: 'rates',
    sources: ['TradingView', 'FRED'],
    description: '미국 10년물 국채 수익률',
    why: '급등 = 위험자산 압박. 하락 = 유동성 증가 → BTC 상방.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://fred.stlouisfed.org/series/DGS10',
    externalLabel: 'FRED',
    tags: ['treasury', '10year', 'yield', 'rates', 'risk_free', 'macro'],
    popularity: 3,
  },
  {
    id: 'cpi',
    name: 'CPI (Consumer Price Index)',
    shortName: 'CPI',
    category: 'macro',
    subcategory: 'inflation',
    sources: ['FRED', 'BLS'],
    description: '미국 소비자물가지수. 인플레이션 척도.',
    why: 'CPI 하락 = 금리 인하 기대 = 위험자산 선호. BTC 가격에 직접 영향.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://fred.stlouisfed.org/series/CPIAUCSL',
    externalLabel: 'FRED',
    tags: ['cpi', 'inflation', 'consumer', 'price', 'fed', 'rates'],
    popularity: 3,
  },
  {
    id: 'fed_rate',
    name: 'Federal Funds Rate',
    shortName: 'Fed Rate',
    category: 'macro',
    subcategory: 'rates',
    sources: ['FRED'],
    description: '미 연준 기준금리. 모든 위험자산 방향성 결정.',
    why: '인하 = BTC/위험자산 강세. 인상 = 약세. 연준 발표 전후 변동성 급증.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://fred.stlouisfed.org/series/FEDFUNDS',
    externalLabel: 'FRED',
    tags: ['fed', 'rate', 'interest', 'federal', 'fomc', 'policy'],
    popularity: 4,
  },
  {
    id: 'btc_dominance',
    name: 'BTC Dominance',
    shortName: 'BTC Dom',
    category: 'macro',
    subcategory: 'market_structure',
    sources: ['CoinMarketCap', 'TradingView'],
    description: 'BTC 시총 / 전체 암호화폐 시총 비율',
    why: '상승 = BTC 강세 / 알트 약세. 하락 = 알트 시즌 시작 신호.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://coinmarketcap.com/charts/bitcoin-dominance/',
    externalLabel: 'CoinMarketCap',
    tags: ['btc', 'dominance', 'altcoin', 'season', 'market_cap'],
    popularity: 5,
    signal: {
      bullish: 'BTC Dom 상승 (BTC 강세 단계)',
      bearish: 'BTC Dom 하락 (알트 시즌 전환)',
    },
  },
  {
    id: 'total_market_cap',
    name: 'Total Crypto Market Cap',
    shortName: 'Total Mcap',
    category: 'macro',
    subcategory: 'market_structure',
    sources: ['CoinMarketCap', 'TradingView'],
    description: '전체 암호화폐 시가총액 합산',
    why: '시장 전체 사이클 판단. ATH 대비 비율로 사이클 위치 파악.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://coinmarketcap.com/charts/',
    externalLabel: 'CoinMarketCap',
    tags: ['total', 'market_cap', 'crypto', 'cycle', 'ath'],
    popularity: 4,
  },
  {
    id: 'total2',
    name: 'TOTAL2 (Altcoin Market Cap)',
    shortName: 'TOTAL2',
    category: 'macro',
    subcategory: 'market_structure',
    sources: ['TradingView'],
    description: 'BTC 제외 전체 알트코인 시가총액',
    why: 'TOTAL2 ATH 돌파 = 알트 시즌 확인. 알트 포트폴리오 타이밍에 필수.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://www.tradingview.com/symbols/CRYPTOCAP-TOTAL2/',
    externalLabel: 'TradingView',
    tags: ['total2', 'altcoin', 'market_cap', 'alt_season', 'ex_btc'],
    popularity: 4,
  },
  {
    id: 'us_equities_correlation',
    name: 'BTC vs S&P500 Correlation',
    shortName: 'BTC/SPX',
    category: 'macro',
    subcategory: 'correlation',
    sources: ['TradingView'],
    description: 'BTC와 S&P500 가격 상관계수',
    why: '상관관계 강할수록 매크로 이벤트에 민감. 디커플링 = 독자적 강세.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://www.tradingview.com/',
    externalLabel: 'TradingView',
    tags: ['btc', 'sp500', 'correlation', 'macro', 'risk_on', 'decoupling'],
    popularity: 3,
  },

  // ─────────────────────────────────────────────────────────────────────────
  // ADDITIONAL INDICATORS TO REACH 100
  // ─────────────────────────────────────────────────────────────────────────

  {
    id: 'miner_revenue',
    name: 'Miner Revenue',
    shortName: 'Miner Rev',
    category: 'onchain',
    subcategory: 'miner',
    sources: ['CryptoQuant', 'Glassnode'],
    description: '채굴자 총 수익 (블록 보상 + 수수료)',
    why: '수익 감소 시 채굴자 매도 압력 증가. 반감기 영향 분석에 필수.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://cryptoquant.com/asset/btc/chart/miner-flows/miner-revenue',
    externalLabel: 'CryptoQuant',
    tags: ['miner', 'revenue', 'block_reward', 'fee', 'halving'],
    popularity: 3,
  },
  {
    id: 'hash_rate',
    name: 'Hash Rate',
    shortName: 'Hashrate',
    category: 'onchain',
    subcategory: 'miner',
    sources: ['CryptoQuant', 'Glassnode'],
    description: '비트코인 네트워크 총 해시파워',
    why: '해시레이트 상승 = 채굴자 신뢰도 증가. 급락 = 채굴자 이탈 (약세 신호).',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://cryptoquant.com/asset/btc/chart/network-data/hashrate',
    externalLabel: 'CryptoQuant',
    tags: ['hashrate', 'mining', 'network', 'security', 'difficulty'],
    popularity: 3,
  },
  {
    id: 'difficulty_ribbon',
    name: 'Difficulty Ribbon',
    shortName: 'Diff Ribbon',
    category: 'onchain',
    subcategory: 'miner',
    sources: ['LookIntoBitcoin', 'Glassnode'],
    description: '채굴 난이도 MA 다발. 리본 압축 = 채굴자 항복 = 바닥 신호.',
    why: 'Willy Woo가 만든 지표. 채굴자 항복 후 회복 = 강력한 매수 시점.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://lookintobitcoin.com/charts/difficulty-ribbon/',
    externalLabel: 'LookIntoBitcoin',
    tags: ['difficulty', 'ribbon', 'miner', 'capitulation', 'willy_woo'],
    popularity: 3,
  },
  {
    id: 'whale_alert',
    name: 'Whale Alert (Large Transfers)',
    shortName: 'Whale Alert',
    category: 'onchain',
    subcategory: 'whale',
    sources: ['Whale Alert', 'Lookonchain'],
    description: '$1M 이상 대규모 온체인 이동 실시간 알림',
    why: 'X에서 가장 많이 RT되는 온체인 데이터. 거래소 대량 이동은 즉시 반응.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://whale-alert.io/',
    externalLabel: 'Whale Alert',
    tags: ['whale', 'alert', 'large', 'transfer', 'onchain', 'real_time'],
    popularity: 4,
  },
  {
    id: 'nansen_smart_money',
    name: 'Nansen Smart Money',
    shortName: 'Smart Money',
    category: 'onchain',
    subcategory: 'whale',
    sources: ['Nansen'],
    description: 'Smart Money 라벨 지갑의 이동/포지션 추적',
    why: '수익률 높은 지갑들의 집단 행동 선행 탐지. 알파 추적에 최강.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://app.nansen.ai/',
    externalLabel: 'Nansen',
    tags: ['nansen', 'smart_money', 'wallet', 'tracking', 'alpha'],
    popularity: 4,
  },
  {
    id: 'options_max_pain',
    name: 'Options Max Pain',
    shortName: 'Max Pain',
    category: 'derivatives',
    subcategory: 'options',
    sources: ['Deribit', 'Coinglass'],
    description: '만기 시 옵션 매도자 손실 최소화 가격 (최대 고통점)',
    why: '만기일 가격이 Max Pain 근처로 수렴하는 경향. 주간/월간 만기 전 필수.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://coinglass.com/OptionsData',
    externalLabel: 'Coinglass',
    tags: ['options', 'max_pain', 'expiry', 'deribit', 'gamma', 'strike'],
    popularity: 3,
  },
  {
    id: 'options_pcr',
    name: 'Put/Call Ratio',
    shortName: 'PCR',
    category: 'derivatives',
    subcategory: 'options',
    sources: ['Deribit', 'Coinglass'],
    description: '풋옵션 거래량 / 콜옵션 거래량 비율',
    why: '>1 = 하락 방어 우세 (공포). <0.5 = 상승 베팅 우세 (탐욕).',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://coinglass.com/OptionsData',
    externalLabel: 'Coinglass',
    tags: ['put', 'call', 'ratio', 'pcr', 'options', 'sentiment'],
    popularity: 3,
  },
  {
    id: 'options_gamma',
    name: 'Options Gamma Exposure',
    shortName: 'GEX',
    category: 'derivatives',
    subcategory: 'options',
    sources: ['Deribit'],
    description: '시장 조성자의 Gamma 헤징 규모. 가격 자석 효과.',
    why: '양의 GEX = 가격 안정화. 음의 GEX = 변동성 증폭. 핵심 레벨 파악에 필수.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://www.deribit.com/',
    externalLabel: 'Deribit',
    tags: ['gamma', 'exposure', 'gex', 'options', 'market_maker', 'pin'],
    popularity: 3,
  },
  {
    id: 'implied_volatility',
    name: 'Implied Volatility (IV)',
    shortName: 'IV',
    category: 'derivatives',
    subcategory: 'options',
    sources: ['Deribit', 'Coinglass'],
    description: '옵션 시장이 예상하는 미래 변동성',
    why: 'IV 급등 = 시장 공포. IV 바닥 = 폭발적 움직임 전조. BVIV(Bitcoin VIX).',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://coinglass.com/OptionsData',
    externalLabel: 'Coinglass',
    tags: ['iv', 'implied', 'volatility', 'bviv', 'options', 'fear'],
    popularity: 3,
  },
  {
    id: 'yield_farming',
    name: 'Yield / APR by Protocol',
    shortName: 'APR',
    category: 'defi',
    subcategory: 'yield',
    sources: ['DefiLlama'],
    description: '프로토콜별 유동성 공급 수익률',
    why: '고APR = 단기 인플레이션 위험. 지속 가능한 APR 파악에 필수.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://defillama.com/yields',
    externalLabel: 'DefiLlama',
    tags: ['yield', 'apr', 'farming', 'liquidity', 'defi', 'staking'],
    popularity: 3,
  },
  {
    id: 'lending_rates',
    name: 'Lending Rates (Aave/Compound)',
    shortName: 'Lending',
    category: 'defi',
    subcategory: 'lending',
    sources: ['DefiLlama', 'Aave'],
    description: '대출 프로토콜 대출/예금 이자율',
    why: '급등 = 레버리지 수요 급증 = 위험 신호 or 강세 신호.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://defillama.com/yields',
    externalLabel: 'DefiLlama',
    tags: ['lending', 'borrowing', 'aave', 'compound', 'interest', 'defi'],
    popularity: 3,
  },
  {
    id: 'defi_revenues',
    name: 'DeFi Protocol Revenue',
    shortName: 'DeFi Rev',
    category: 'defi',
    subcategory: 'revenue',
    sources: ['Token Terminal'],
    description: '개별 DeFi 프로토콜 실제 수익 (Treasury 수취 분)',
    why: 'P/S Ratio 계산 기반. 수익 대비 가격 평가에 필수.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://tokenterminal.com/',
    externalLabel: 'Token Terminal',
    tags: ['revenue', 'protocol', 'defi', 'ps_ratio', 'token_terminal'],
    popularity: 3,
  },
  {
    id: 'solana_tps',
    name: 'Solana TPS (Transactions Per Second)',
    shortName: 'SOL TPS',
    category: 'onchain',
    subcategory: 'network_activity',
    sources: ['Solana Beach', 'Dune'],
    description: '솔라나 네트워크 초당 처리 트랜잭션 수',
    why: 'SOL 생태계 활동 직접 지표. 밈코인 시즌 또는 NFT 붐 때 급등.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://solanabeach.io/',
    externalLabel: 'Solana Beach',
    tags: ['solana', 'tps', 'throughput', 'transactions', 'network'],
    popularity: 3,
  },
  {
    id: 'eth_gas',
    name: 'Ethereum Gas Price',
    shortName: 'ETH Gas',
    category: 'onchain',
    subcategory: 'network_activity',
    sources: ['Etherscan', 'CryptoQuant'],
    description: '이더리움 네트워크 가스비 (Gwei)',
    why: '가스비 급등 = 네트워크 붐빔 = 강한 수요. ETH 소각량 증가.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://etherscan.io/gastracker',
    externalLabel: 'Etherscan',
    tags: ['ethereum', 'gas', 'gwei', 'fee', 'burn', 'eip1559'],
    popularity: 3,
  },
  {
    id: 'eth_supply',
    name: 'ETH Net Issuance / Deflation',
    shortName: 'ETH Supply',
    category: 'onchain',
    subcategory: 'supply',
    sources: ['Ultrasound.money'],
    description: '이더리움 순발행량. EIP-1559 소각 - 신규 발행.',
    why: '소각량 > 발행량 = 디플레이션 ETH. 스테이킹 수익률과 함께 봐야 함.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://ultrasound.money/',
    externalLabel: 'Ultrasound.money',
    tags: ['eth', 'supply', 'burn', 'deflation', 'issuance', 'eip1559'],
    popularity: 3,
  },
  {
    id: 'l2_activity',
    name: 'Layer 2 TVL & Activity',
    shortName: 'L2 Activity',
    category: 'defi',
    subcategory: 'layer2',
    sources: ['L2Beat', 'DefiLlama'],
    description: 'Arbitrum, Base, Optimism 등 L2 TVL + 활성 주소',
    why: 'L2 활성화 = ETH 생태계 성장 = ETH 중장기 강세 근거.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://l2beat.com/',
    externalLabel: 'L2Beat',
    tags: ['layer2', 'l2', 'arbitrum', 'base', 'optimism', 'tvl', 'scaling'],
    popularity: 3,
  },
  {
    id: 'nft_volume',
    name: 'NFT Trading Volume',
    shortName: 'NFT Vol',
    category: 'defi',
    subcategory: 'nft',
    sources: ['OpenSea', 'Dune'],
    description: '전체 NFT 마켓플레이스 거래량',
    why: 'NFT 시장 활성화 = 리테일 sentiment 지표. 사이클 후반 급증.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://dune.com/nft',
    externalLabel: 'Dune Analytics',
    tags: ['nft', 'trading', 'volume', 'opensea', 'retail', 'sentiment'],
    popularity: 3,
  },
  {
    id: 'mempool_size',
    name: 'Bitcoin Mempool Size',
    shortName: 'Mempool',
    category: 'onchain',
    subcategory: 'network_activity',
    sources: ['Mempool.space'],
    description: '미확인 트랜잭션 대기 풀 크기',
    why: '급증 = 네트워크 활동 폭발. 수수료 급등 전조. 거래소 입출금 지연 예측.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://mempool.space/',
    externalLabel: 'Mempool.space',
    tags: ['mempool', 'bitcoin', 'fee', 'congestion', 'transaction', 'pending'],
    popularity: 3,
  },
  {
    id: 'stock_to_flow',
    name: 'Stock-to-Flow (S2F)',
    shortName: 'S2F',
    category: 'macro',
    subcategory: 'monetary',
    sources: ['LookIntoBitcoin'],
    description: 'BTC 현재 공급량 / 연간 신규 발행량 비율',
    why: '반감기마다 S2F 2배 증가 → 희소성 급증. 장기 가격 모델.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://lookintobitcoin.com/charts/stock-to-flow-model/',
    externalLabel: 'LookIntoBitcoin',
    tags: ['stock_to_flow', 's2f', 'scarcity', 'halving', 'model'],
    popularity: 3,
  },
  {
    id: 'rainbow_chart',
    name: 'Bitcoin Rainbow Chart',
    shortName: 'Rainbow',
    category: 'macro',
    subcategory: 'market_cycle',
    sources: ['Blockchaincenter.net'],
    description: 'BTC 로그 성장 곡선 기반 사이클 위치 시각화',
    why: '장기 트레이더들이 사이클 단계(HODLing → Sell) 판단에 활용.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://www.blockchaincenter.net/en/bitcoin-rainbow-chart/',
    externalLabel: 'Blockchaincenter',
    tags: ['rainbow', 'chart', 'cycle', 'log', 'growth', 'long_term'],
    popularity: 3,
  },
  {
    id: 'puell_multiple',
    name: 'Puell Multiple',
    shortName: 'Puell',
    category: 'onchain',
    subcategory: 'miner',
    sources: ['LookIntoBitcoin', 'Glassnode'],
    description: '일간 채굴 수익 / 365일 평균 채굴 수익',
    why: '극단적 높음 = 채굴자 매도 피크 → 천장. 극단적 낮음 = 채굴자 항복 → 바닥.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://lookintobitcoin.com/charts/puell-multiple/',
    externalLabel: 'LookIntoBitcoin',
    tags: ['puell', 'multiple', 'miner', 'revenue', 'cycle'],
    popularity: 3,
  },
  {
    id: 'reserve_risk',
    name: 'Reserve Risk',
    shortName: 'Reserve Risk',
    category: 'onchain',
    subcategory: 'market_cycle',
    sources: ['LookIntoBitcoin', 'Glassnode'],
    description: '장기 홀더 신뢰도 대비 가격 리스크 비율',
    why: '바닥에서 낮음, 천장에서 높음. 장기 진입 타이밍에 활용.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://lookintobitcoin.com/charts/reserve-risk/',
    externalLabel: 'LookIntoBitcoin',
    tags: ['reserve', 'risk', 'hodl', 'long_term', 'cycle'],
    popularity: 3,
  },
  {
    id: 'on_chain_transaction_fees',
    name: 'Transaction Fees (BTC/ETH)',
    shortName: 'TX Fees',
    category: 'onchain',
    subcategory: 'network_activity',
    sources: ['CryptoQuant', 'Glassnode'],
    description: '네트워크 총 트랜잭션 수수료 합산',
    why: '수수료 급증 = 활동 폭발 (강세 신호). ETH EIP-1559 소각량 결정.',
    displayType: 'external',
    tier: 'C',
    externalUrl: 'https://cryptoquant.com/asset/btc/chart/network-data/transaction-fees',
    externalLabel: 'CryptoQuant',
    tags: ['transaction', 'fees', 'fee', 'network', 'activity', 'burn'],
    popularity: 3,
  },
  {
    id: 'liq_side_depth',
    name: 'Liquidation Side Depth',
    shortName: 'Liq Depth',
    category: 'derivatives',
    subcategory: 'liquidation',
    sources: ['Engine', 'Coinglass'],
    description: '현재가 기준 상/하단 주요 청산 레벨 + 규모',
    why: '어느 방향으로 더 많은 청산이 쌓여 있는지 = 가격 자석 방향.',
    displayType: 'engine',
    tier: 'A',
    tags: ['liquidation', 'depth', 'side', 'magnet', 'squeeze'],
    popularity: 4,
    signal: {
      bullish: '상단 롱 청산 > 하단 숏 청산 (숏 스퀴즈 가능성)',
      bearish: '하단 숏 청산 > 상단 롱 청산 (롱 청산 가능성)',
    },
  },
];

// ─── Helper functions ─────────────────────────────────────────────────────

export const CATEGORIES: { key: IndicatorCategory; label: string; icon: string }[] = [
  { key: 'onchain',     label: 'On-Chain',   icon: '⛓' },
  { key: 'derivatives', label: 'Derivatives', icon: '📊' },
  { key: 'defi',        label: 'DeFi',        icon: '🔷' },
  { key: 'technical',   label: 'Technical',   icon: '📈' },
  { key: 'sentiment',   label: 'Sentiment',   icon: '💬' },
  { key: 'macro',       label: 'Macro',       icon: '🌍' },
];

export type FilterMode = 'all' | IndicatorCategory | 'tier_a' | 'popular';

/** Search + filter indicators */
export function searchIndicators(
  query: string,
  filter: FilterMode = 'all',
  limit = 100,
): IndicatorDef[] {
  const q = query.trim().toLowerCase().replace(/[\s_-]/g, '');

  let pool = INDICATOR_REGISTRY;

  // Category filter
  if (filter === 'tier_a') {
    pool = pool.filter((i) => i.tier === 'A');
  } else if (filter === 'popular') {
    pool = pool.filter((i) => i.popularity >= 4);
  } else if (filter !== 'all') {
    pool = pool.filter((i) => i.category === filter);
  }

  if (!q) {
    return pool.sort((a, b) => b.popularity - a.popularity).slice(0, limit);
  }

  // Fuzzy score
  function score(ind: IndicatorDef): number {
    const id     = ind.id.replace(/[\s_-]/g, '');
    const name   = ind.name.toLowerCase().replace(/[\s_-]/g, '');
    const short  = ind.shortName.toLowerCase().replace(/[\s_-]/g, '');
    const desc   = ind.description.toLowerCase();
    const tags   = ind.tags.join(' ').replace(/[\s_-]/g, '');

    if (id === q || name === q)       return 100;
    if (id.startsWith(q) || name.startsWith(q) || short.startsWith(q)) return 90;
    if (id.includes(q) || name.includes(q) || short.includes(q))       return 80;
    if (tags.includes(q))                                                return 70;
    if (desc.includes(q.substring(0, Math.max(q.length - 1, 2))))       return 50;
    return 0;
  }

  return pool
    .map((i) => ({ i, s: score(i) }))
    .filter(({ s }) => s > 0)
    .sort((a, b) => b.s - a.s || b.i.popularity - a.i.popularity)
    .slice(0, limit)
    .map(({ i }) => i);
}

/** Group by category */
export function groupByCategory(
  items: IndicatorDef[],
): Record<IndicatorCategory, IndicatorDef[]> {
  const result = {} as Record<IndicatorCategory, IndicatorDef[]>;
  for (const cat of CATEGORIES) result[cat.key] = [];
  for (const item of items) result[item.category].push(item);
  return result;
}

/** Indicators already supported by our engine (Tier A) */
export const ENGINE_INDICATORS = INDICATOR_REGISTRY.filter((i) => i.tier === 'A');

/** Tier A engine keys */
export const ENGINE_KEY_MAP: Record<string, IndicatorDef> = Object.fromEntries(
  ENGINE_INDICATORS.filter((i) => i.engineKey).map((i) => [i.engineKey!, i]),
);
