/**
 * INDICATOR_REGISTRY — declarative metadata for all indicators.
 *
 * Add here to expose a new indicator to the UI.
 * The dispatcher (IndicatorRenderer.svelte) reads this at render time.
 *
 * Phase 1 entries: the set the UI needs *now* to replace hardcoded evidenceItems.
 * Phase 2 will register the remaining 70+ building blocks wholesale.
 */

import type { IndicatorDef, IndicatorFamily, IndicatorArchetype } from './types';

export const INDICATOR_REGISTRY: Record<string, IndicatorDef> = {
  // ── OI family ───────────────────────────────────────────────────
  oi_change_1h: {
    id: 'oi_change_1h',
    label: 'OI 1h',
    family: 'OI',
    archetype: 'A',
    dimensions: ['horizon', 'percentile'],
    source: { provider: 'coinalyze', endpoint: '/oi/delta?horizon=1h' },
    thresholds: { warn: 50, extreme: 90, historical: 98 },
    priority: 0,
    defaultVisible: true,
    unit: '%',
    relatedBlocks: ['oi_change', 'oi_acceleration', 'oi_hold_after_spike'],
    description: 'Open interest delta — 1h change; percentile vs 30-day distribution',
    aiSynonyms: ['oi', 'open interest', '오아이', '미결제약정', 'oi 1h', 'oi 변화'],
    aiExampleQueries: ['OI 보여줘', 'open interest 1h', 'OI 급증?'],
    alternateArchetypes: ['D'],
  },

  oi_change_4h: {
    id: 'oi_change_4h',
    label: 'OI 4h',
    family: 'OI',
    archetype: 'A',
    dimensions: ['horizon', 'percentile'],
    source: { provider: 'coinalyze', endpoint: '/oi/delta?horizon=4h' },
    thresholds: { warn: 50, extreme: 90, historical: 98 },
    priority: 1,
    defaultVisible: true,
    unit: '%',
    aiSynonyms: ['oi 4h', 'open interest 4h', '오아이 4h'],
    aiExampleQueries: ['OI 4h 어때?'],
    alternateArchetypes: ['D'],
  },

  oi_per_venue: {
    id: 'oi_per_venue',
    label: 'OI / venue',
    family: 'OI',
    archetype: 'F',
    dimensions: ['venue', 'horizon'],
    source: { provider: 'coinalyze', endpoint: '/oi/per-venue' },
    priority: 0,
    defaultVisible: true,
    unit: '%',
    relatedBlocks: [
      'oi_exchange_divergence',
      'venue_oi_divergence_bull',
      'venue_oi_divergence_bear',
      'isolated_venue_pump',
    ],
    description: 'OI change across Binance / Bybit / OKX — divergence = isolated leverage',
    aiSynonyms: ['oi venue', 'oi by exchange', 'exchange oi', 'venue oi divergence', '거래소별 oi'],
    aiExampleQueries: ['거래소별 OI 보여줘', 'venue oi divergence?'],
    alternateArchetypes: ['A'],
  },

  // ── Funding family ──────────────────────────────────────────────
  funding_rate: {
    id: 'funding_rate',
    label: 'Funding',
    family: 'Funding',
    archetype: 'A',
    dimensions: ['horizon', 'percentile', 'regime'],
    source: { provider: 'coinalyze', endpoint: '/funding' },
    thresholds: { warn: 60, extreme: 92, historical: 99 },
    priority: 0,
    defaultVisible: true,
    unit: '%',
    relatedBlocks: [
      'funding_extreme',
      'funding_flip',
      'positive_funding_bias',
      'negative_funding_bias',
    ],
    description: 'Perpetual funding rate — percentile vs 30d; regime-aware extreme bands',
    aiSynonyms: ['funding', 'funding rate', '펀딩', '펀딩율', 'fr', 'perp funding'],
    aiExampleQueries: ['펀딩 보여줘', 'funding rate 어때?', 'funding 지금 어느 수준?'],
    alternateArchetypes: ['F'],
  },

  funding_per_venue: {
    id: 'funding_per_venue',
    label: 'Funding / venue',
    family: 'Funding',
    archetype: 'F',
    dimensions: ['venue'],
    source: { provider: 'coinalyze', endpoint: '/funding/per-venue' },
    priority: 1,
    defaultVisible: true,
    unit: '%',
    relatedBlocks: ['venue_funding_spread_extreme'],
    aiSynonyms: ['venue funding', 'funding spread', 'funding per exchange', '거래소별 펀딩'],
    aiExampleQueries: ['거래소별 펀딩 차이?', 'funding spread 확인'],
    alternateArchetypes: ['A'],
  },

  // ── CVD family ──────────────────────────────────────────────────
  cvd_state: {
    id: 'cvd_state',
    label: 'CVD',
    family: 'CVD',
    archetype: 'D',
    dimensions: ['side'],
    source: { provider: 'derived' },
    thresholds: { warn: 60, extreme: 90 },
    priority: 0,
    defaultVisible: true,
    unit: '',
    relatedBlocks: ['cvd_price_divergence', 'delta_flip_positive', 'delta_flip_negative'],
    description: 'Cumulative volume delta — divergence vs price is the alpha',
    aiSynonyms: ['cvd', 'cumulative volume delta', 'delta', '델타', '누적델타', 'volume delta'],
    aiExampleQueries: ['CVD 다이버전스?', 'delta 지금 어때', 'cvd 보여줘'],
    alternateArchetypes: ['A'],
  },

  // ── Volume family ───────────────────────────────────────────────
  volume_ratio: {
    id: 'volume_ratio',
    label: 'Vol',
    family: 'Volume',
    archetype: 'A',
    dimensions: ['percentile'],
    source: { provider: 'derived' },
    thresholds: { warn: 60, extreme: 90, historical: 98 },
    priority: 1,
    defaultVisible: true,
    unit: 'x',
    relatedBlocks: ['volume_spike', 'volume_dryup', 'volume_surge_bull', 'volume_surge_bear'],
    aiSynonyms: ['volume', 'vol', '거래량', 'volume ratio', '볼륨'],
    aiExampleQueries: ['거래량 체크', 'volume 이상 있어?'],
  },

  // ── Premium (Pillar 1 of our existing assets) ───────────────────
  coinbase_premium: {
    id: 'coinbase_premium',
    label: 'Coinbase Prem',
    family: 'Premium',
    archetype: 'A',
    dimensions: ['percentile'],
    source: { provider: 'derived' },
    thresholds: { warn: 60, extreme: 90 },
    priority: 1,
    defaultVisible: false,
    unit: '%',
    relatedBlocks: ['coinbase_premium_positive', 'coinbase_premium_weak'],
    description: 'Coinbase–Binance price gap — US institutional bid proxy',
    aiSynonyms: ['coinbase premium', 'cb premium', 'cbp', '코인베이스 프리미엄', 'us premium'],
    aiExampleQueries: ['coinbase premium 지금?', 'US 기관 매수세 확인'],
    alternateArchetypes: ['D'],
  },

  // ── Liquidations (Pillar 1 — W-0122-B) ─────────────────────────
  liq_heatmap: {
    id: 'liq_heatmap',
    label: 'Liq map',
    family: 'Liquidations',
    archetype: 'C',
    dimensions: ['price_level', 'venue', 'side'],
    source: { provider: 'binance', stream: '!forceOrder@arr' },
    priority: 0,
    defaultVisible: true,
    relatedBlocks: [
      'liq_zone_squeeze_setup',
      'liq_magnet_above',
      'liq_magnet_below',
      'multi_venue_liq_cascade',
    ],
    description: 'Liquidation clusters — price×time heatmap. Clusters act as magnets.',
    aiSynonyms: ['liq', 'liquidation', 'liq heatmap', '청산', '청산히트맵', 'liquidation map', 'liq cluster'],
    aiExampleQueries: ['청산 히트맵 보여줘', 'liq cluster 어디?', '청산 매그넷 확인'],
    alternateArchetypes: ['I'],
  },

  // ── Options (Pillar 2 — W-0122-C) ──────────────────────────────
  options_skew_25d: {
    id: 'options_skew_25d',
    label: 'Skew 25d',
    family: 'Options',
    archetype: 'A',
    dimensions: ['percentile'],
    source: { provider: 'deribit', endpoint: '/api/market/options-snapshot' },
    thresholds: { warn: 60, extreme: 90, historical: 98 },
    priority: 1,
    defaultVisible: true,
    unit: 'pts',
    relatedBlocks: ['skew_extreme_fear', 'skew_extreme_greed'],
    description: 'Deribit 25-delta skew proxy (OTM put IV − OTM call IV). Positive = fear priced in.',
    aiSynonyms: ['skew', '스큐', '25d skew', 'put call skew', 'options skew', 'iv skew', '변동성 스큐'],
    aiExampleQueries: ['skew 보여줘', '스큐 지금 어때?', '옵션 공포 측정'],
    alternateArchetypes: ['G'],
  },

  gamma_flip_level: {
    id: 'gamma_flip_level',
    label: 'Gamma flip',
    family: 'Options',
    archetype: 'E',
    dimensions: ['price_level', 'regime'],
    source: { provider: 'deribit', endpoint: '/options/gex' },
    priority: 0,
    defaultVisible: false,
    relatedBlocks: ['gamma_flip_proximity'],
    description: 'Market-maker gamma flip price. Above = pin; below = trend.',
    aiSynonyms: ['gamma', 'gamma flip', '감마', '감마플립', 'gex', 'gamma exposure', 'gamma pin'],
    aiExampleQueries: ['gamma pin 이 뭐야?', '감마 플립 레벨?', 'gex 확인'],
    alternateArchetypes: ['I'],
  },

  put_call_ratio: {
    id: 'put_call_ratio',
    label: 'P/C',
    family: 'Options',
    archetype: 'A',
    dimensions: ['percentile'],
    source: { provider: 'deribit', endpoint: '/api/market/options-snapshot' },
    thresholds: { warn: 60, extreme: 90 },
    priority: 2,
    defaultVisible: true,
    unit: '',
    relatedBlocks: ['put_call_ratio_extreme'],
    description: 'Put/Call open interest ratio from Deribit — >1 = put-heavy, <1 = call-heavy',
    aiSynonyms: ['put call ratio', 'pcr', 'p/c', 'put/call', '풋콜비율'],
    aiExampleQueries: ['put call ratio 어때?', 'pcr 확인'],
  },

  // ── Netflow (Pillar 4 — W-0122-D) ──────────────────────────────
  exchange_netflow: {
    id: 'exchange_netflow',
    label: 'Netflow',
    family: 'Netflow',
    archetype: 'H',
    dimensions: ['venue', 'horizon', 'percentile'],
    source: { provider: 'arkham', endpoint: '/netflow/{exchange}' },
    thresholds: { warn: 70, extreme: 92 },
    priority: 1,
    defaultVisible: false,
    unit: 'USD',
    relatedBlocks: [
      'exchange_netflow_inflow_spike',
      'exchange_netflow_outflow_persistent',
      'whale_transfer_to_exchange',
    ],
    description: 'Exchange netflow via Arkham — inflow = sell pressure, outflow = hodl',
    aiSynonyms: ['netflow', 'exchange netflow', '넷플로우', '거래소 유입', '코인 유출', 'on-chain flow'],
    aiExampleQueries: ['거래소 유입 확인', 'netflow 지금?', '고래 거래소 이동?'],
    alternateArchetypes: ['A'],
  },

  // ── Netflow derived ──────────────────────────────────────────────────
  funding_term_structure: {
    id: 'funding_term_structure',
    label: 'Fund curve',
    family: 'Funding',
    archetype: 'G',
    dimensions: ['horizon'],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    unit: '%',
    description: 'Funding rate across tenors (8h/1d/7d/30d/90d) — contango vs backwardation',
    aiSynonyms: ['funding curve', 'funding term structure', '펀딩 커브', '선물 베이시스 커브'],
    aiExampleQueries: ['funding curve 어때?', '펀딩 장기 추세?'],
  },

  // ── Liquidations derived ─────────────────────────────────────────────
  liq_by_level: {
    id: 'liq_by_level',
    label: 'Liq levels',
    family: 'Liquidations',
    archetype: 'I',
    dimensions: ['price_level', 'side'],
    source: { provider: 'derived' },
    priority: 1,
    defaultVisible: false,
    description: 'Liquidation notional by price level — shows magnet zones as histogram',
    aiSynonyms: ['liq by level', 'liquidation histogram', '청산 레벨', 'liq histogram'],
    aiExampleQueries: ['청산 레벨 분포?', 'liq histogram'],
    alternateArchetypes: ['C'],
  },

  // ── Whale events ────────────────────────────────────────────────────
  whale_transfers: {
    id: 'whale_transfers',
    label: 'Whale moves',
    family: 'Netflow',
    archetype: 'J',
    dimensions: ['venue', 'side'],
    source: { provider: 'arkham', endpoint: '/transfers' },
    priority: 3,
    defaultVisible: false,
    description: 'Large wallet transfers — Phase 2 Arkham integration',
    aiSynonyms: ['whale', '고래', '고래 이동', 'whale transfer', 'large transfer'],
    aiExampleQueries: ['고래 이동?', 'whale 거래소 이동?'],
    alternateArchetypes: ['H'],
  },

  stablecoin_supply_ratio: {
    id: 'stablecoin_supply_ratio',
    label: 'SSR',
    family: 'Netflow',
    archetype: 'A',
    dimensions: ['percentile'],
    source: { provider: 'derived', endpoint: '/api/market/stablecoin-ssr' },
    thresholds: { warn: 60, extreme: 90 },
    priority: 2,
    defaultVisible: true,
    unit: '',
    description: 'BTC mcap / stablecoin supply — low = dry powder on sidelines (bullish setup)',
    aiSynonyms: ['ssr', 'stablecoin ratio', 'stablecoin supply', '스테이블코인 비율', 'dry powder'],
    aiExampleQueries: ['dry powder 확인', 'ssr 지금?'],
  },

  // ── Volatility (Pillar-adjacent free win — W-0122-F) ────────────
  realized_vol_cone: {
    id: 'realized_vol_cone',
    label: 'RV 30d',
    family: 'Volatility',
    archetype: 'A',
    dimensions: ['percentile'],
    source: { provider: 'derived', endpoint: '/api/market/rv-cone' },
    thresholds: { warn: 60, extreme: 90, historical: 98 },
    priority: 1,
    defaultVisible: true,
    unit: '%',
    relatedBlocks: ['atr_ultra_low', 'bollinger_squeeze', 'bollinger_expansion'],
    description: 'Annualized 30d realized volatility vs 180d cone. Low = compression setup.',
  },

  // ── Funding regime flip (Archetype E — W-0122-F) ────────────────
  funding_flip: {
    id: 'funding_flip',
    label: 'Funding regime',
    family: 'Funding',
    archetype: 'E',
    dimensions: ['regime'],
    source: { provider: 'binance', endpoint: '/api/market/funding-flip' },
    priority: 0,
    defaultVisible: true,
    relatedBlocks: ['funding_flip', 'positive_funding_bias', 'negative_funding_bias'],
    description: 'Time since last funding sign flip — fresh flips unwind one-sided leverage.',
  },

  // ── TV TA indicators (Phase 1A, W-0400) — client-calculated ────────────────

  rsi: {
    id: 'rsi',
    label: 'RSI',
    family: 'RelativeStrength',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 1,
    defaultVisible: false,
    engineKey: 'rsi',
    category: 'TA',
    paramSchema: {
      period: { type: 'number', default: 14, min: 2, max: 100, step: 1, label: 'Period' },
    },
    description: 'Relative Strength Index — momentum oscillator (0–100)',
    aiSynonyms: ['rsi', '상대강도', '알에스아이', '상대강도지수', 'relative strength'],
    aiExampleQueries: ['RSI 보여줘', 'RSI 14', '과매수 과매도'],
  },

  macd: {
    id: 'macd',
    label: 'MACD',
    family: 'RelativeStrength',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 1,
    defaultVisible: false,
    engineKey: 'macd',
    category: 'TA',
    paramSchema: {
      fast: { type: 'number', default: 12, min: 2, max: 100, step: 1, label: 'Fast' },
      slow: { type: 'number', default: 26, min: 2, max: 200, step: 1, label: 'Slow' },
      signal: { type: 'number', default: 9, min: 2, max: 50, step: 1, label: 'Signal' },
    },
    description: 'Moving Average Convergence Divergence — trend momentum',
    aiSynonyms: ['macd', '맥디', 'moving average convergence', '수렴확산'],
    aiExampleQueries: ['MACD 보여줘', 'MACD 12 26 9', '맥디'],
  },

  ema: {
    id: 'ema',
    label: 'EMA',
    family: 'MovingAverage',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 1,
    defaultVisible: false,
    engineKey: 'ema',
    category: 'TA',
    paramSchema: {
      period: { type: 'number', default: 20, min: 2, max: 500, step: 1, label: 'Period' },
    },
    description: 'Exponential Moving Average — trend line overlay on price',
    aiSynonyms: ['ema', '지수이동평균', '이이엠에이', 'exponential moving average', '이동평균'],
    aiExampleQueries: ['EMA 20', '지수이동평균', 'EMA 추세'],
  },

  bb: {
    id: 'bb',
    label: 'BB',
    family: 'Volatility',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 1,
    defaultVisible: false,
    engineKey: 'bb',
    category: 'TA',
    paramSchema: {
      period: { type: 'number', default: 20, min: 2, max: 200, step: 1, label: 'Period' },
      multiplier: { type: 'number', default: 2, min: 0.5, max: 5, step: 0.5, label: 'Multiplier' },
    },
    description: 'Bollinger Bands — volatility envelope around moving average',
    aiSynonyms: ['bb', '볼린저밴드', '볼린저', 'bollinger bands', 'bollinger'],
    aiExampleQueries: ['볼린저밴드', 'BB 20', '밴드 수축'],
  },

  vwap: {
    id: 'vwap',
    label: 'VWAP',
    family: 'PriceAction',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 1,
    defaultVisible: false,
    engineKey: 'vwap',
    category: 'TA',
    paramSchema: {
      anchor: { type: 'string', default: 'session', label: 'Anchor' },
    },
    description: 'Volume Weighted Average Price — institutional reference price',
    aiSynonyms: ['vwap', '브이왑', '거래량가중평균', 'volume weighted average', '기관'],
    aiExampleQueries: ['VWAP 보여줘', '거래량가중평균', 'VWAP 기준'],
  },

  atr_bands: {
    id: 'atr_bands',
    label: 'ATR Bands',
    family: 'Volatility',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'atr_bands',
    category: 'TA',
    paramSchema: {
      period: { type: 'number', default: 14, min: 2, max: 100, step: 1, label: 'Period' },
      multiplier: { type: 'number', default: 2, min: 0.5, max: 5, step: 0.5, label: 'Multiplier' },
    },
    description: 'ATR-based volatility bands — dynamic support/resistance',
    aiSynonyms: ['atr', 'atr bands', '에이티알', '평균진폭', 'average true range'],
    aiExampleQueries: ['ATR bands', 'ATR 밴드', '변동성 밴드'],
  },

  volume_ta: {
    id: 'volume_ta',
    label: 'Volume',
    family: 'Volume',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 1,
    defaultVisible: false,
    engineKey: 'volume',
    category: 'TA',
    description: 'Bar volume histogram — raw trade volume per candle',
    aiSynonyms: ['volume', '거래량', '볼륨', '체결량'],
    aiExampleQueries: ['거래량', 'volume 보여줘', '볼륨'],
  },

  oi_ta: {
    id: 'oi_ta',
    label: 'OI Chart',
    family: 'OI',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 1,
    defaultVisible: false,
    engineKey: 'oi',
    category: 'TA',
    paramSchema: {
      maWindow: { type: 'number', default: 14, min: 2, max: 100, step: 1, label: 'MA Window' },
    },
    description: 'Open interest as chart sub-pane with MA overlay',
    aiSynonyms: ['oi chart', 'oi 차트', '미결제약정 차트', 'open interest chart'],
    aiExampleQueries: ['OI 차트', 'open interest 차트'],
  },

  cvd_ta: {
    id: 'cvd_ta',
    label: 'CVD',
    family: 'CVD',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 1,
    defaultVisible: false,
    engineKey: 'cvd',
    category: 'TA',
    paramSchema: {
      maWindow: { type: 'number', default: 14, min: 2, max: 100, step: 1, label: 'MA Window' },
    },
    description: 'Cumulative Volume Delta — buy/sell pressure divergence',
    aiSynonyms: ['cvd', '씨브이디', '누적거래량델타', 'cumulative volume delta', '델타'],
    aiExampleQueries: ['CVD 차트', '누적거래량', '매수매도 압력'],
  },

  derivatives_ta: {
    id: 'derivatives_ta',
    label: 'Derivatives',
    family: 'Funding',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'derivatives',
    category: 'TA',
    paramSchema: {
      maWindow: { type: 'number', default: 14, min: 2, max: 100, step: 1, label: 'MA Window' },
    },
    description: 'Derivatives data sub-pane — funding + OI composite',
    aiSynonyms: ['derivatives', '파생', '파생상품', 'futures data', '선물'],
    aiExampleQueries: ['파생 데이터', 'derivatives 차트', '선물 지표'],
  },

  // ── Moving Averages (engine TA, Phase 2B) ─────────────────────────────────

  sma_5: {
    id: 'sma_5',
    label: 'SMA 5',
    family: 'MovingAverage',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'sma_5',
    category: 'TA',
    paramSchema: {
      length: { type: 'number', default: 5, min: 1, max: 500, step: 1, label: 'Length' },
    },
    description: 'Simple Moving Average (5 period)',
    aiSynonyms: ['sma 5', 'simple moving average 5', '단순이동평균 5'],
  },

  sma_9: {
    id: 'sma_9',
    label: 'SMA 9',
    family: 'MovingAverage',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'sma_9',
    category: 'TA',
    paramSchema: {
      length: { type: 'number', default: 9, min: 1, max: 500, step: 1, label: 'Length' },
    },
    description: 'Simple Moving Average (9 period)',
    aiSynonyms: ['sma 9', 'simple moving average 9'],
  },

  sma_10: {
    id: 'sma_10',
    label: 'SMA 10',
    family: 'MovingAverage',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'sma_10',
    category: 'TA',
    paramSchema: {
      length: { type: 'number', default: 10, min: 1, max: 500, step: 1, label: 'Length' },
    },
    description: 'Simple Moving Average (10 period)',
    aiSynonyms: ['sma 10', 'simple moving average 10'],
  },

  sma_14: {
    id: 'sma_14',
    label: 'SMA 14',
    family: 'MovingAverage',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'sma_14',
    category: 'TA',
    paramSchema: {
      length: { type: 'number', default: 14, min: 1, max: 500, step: 1, label: 'Length' },
    },
    description: 'Simple Moving Average (14 period)',
    aiSynonyms: ['sma 14', 'simple moving average 14'],
  },

  sma_20: {
    id: 'sma_20',
    label: 'SMA 20',
    family: 'MovingAverage',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'sma_20',
    category: 'TA',
    paramSchema: {
      length: { type: 'number', default: 20, min: 1, max: 500, step: 1, label: 'Length' },
    },
    description: 'Simple Moving Average (20 period)',
    aiSynonyms: ['sma 20', 'simple moving average 20', '단순이동평균 20'],
  },

  sma_30: {
    id: 'sma_30',
    label: 'SMA 30',
    family: 'MovingAverage',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'sma_30',
    category: 'TA',
    paramSchema: {
      length: { type: 'number', default: 30, min: 1, max: 500, step: 1, label: 'Length' },
    },
    description: 'Simple Moving Average (30 period)',
    aiSynonyms: ['sma 30', 'simple moving average 30'],
  },

  sma_50: {
    id: 'sma_50',
    label: 'SMA 50',
    family: 'MovingAverage',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'sma_50',
    category: 'TA',
    paramSchema: {
      length: { type: 'number', default: 50, min: 1, max: 500, step: 1, label: 'Length' },
    },
    description: 'Simple Moving Average (50 period)',
    aiSynonyms: ['sma 50', 'simple moving average 50', '단순이동평균 50', '골든크로스'],
  },

  sma_100: {
    id: 'sma_100',
    label: 'SMA 100',
    family: 'MovingAverage',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'sma_100',
    category: 'TA',
    paramSchema: {
      length: { type: 'number', default: 100, min: 1, max: 500, step: 1, label: 'Length' },
    },
    description: 'Simple Moving Average (100 period)',
    aiSynonyms: ['sma 100', 'simple moving average 100'],
  },

  sma_200: {
    id: 'sma_200',
    label: 'SMA 200',
    family: 'MovingAverage',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'sma_200',
    category: 'TA',
    paramSchema: {
      length: { type: 'number', default: 200, min: 1, max: 500, step: 1, label: 'Length' },
    },
    description: 'Simple Moving Average (200 period) — long-term trend reference',
    aiSynonyms: ['sma 200', 'simple moving average 200', '200일 이동평균', '장기 추세'],
  },

  ema_5: {
    id: 'ema_5',
    label: 'EMA 5',
    family: 'MovingAverage',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'ema_5',
    category: 'TA',
    paramSchema: {
      length: { type: 'number', default: 5, min: 1, max: 500, step: 1, label: 'Length' },
    },
    description: 'Exponential Moving Average (5 period)',
    aiSynonyms: ['ema 5', 'exponential moving average 5'],
  },

  ema_8: {
    id: 'ema_8',
    label: 'EMA 8',
    family: 'MovingAverage',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'ema_8',
    category: 'TA',
    paramSchema: {
      length: { type: 'number', default: 8, min: 1, max: 500, step: 1, label: 'Length' },
    },
    description: 'Exponential Moving Average (8 period)',
    aiSynonyms: ['ema 8', 'exponential moving average 8'],
  },

  ema_9: {
    id: 'ema_9',
    label: 'EMA 9',
    family: 'MovingAverage',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'ema_9',
    category: 'TA',
    paramSchema: {
      length: { type: 'number', default: 9, min: 1, max: 500, step: 1, label: 'Length' },
    },
    description: 'Exponential Moving Average (9 period)',
    aiSynonyms: ['ema 9', 'exponential moving average 9'],
  },

  ema_12: {
    id: 'ema_12',
    label: 'EMA 12',
    family: 'MovingAverage',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'ema_12',
    category: 'TA',
    paramSchema: {
      length: { type: 'number', default: 12, min: 1, max: 500, step: 1, label: 'Length' },
    },
    description: 'Exponential Moving Average (12 period)',
    aiSynonyms: ['ema 12', 'exponential moving average 12'],
  },

  ema_20: {
    id: 'ema_20',
    label: 'EMA 20',
    family: 'MovingAverage',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'ema_20',
    category: 'TA',
    paramSchema: {
      length: { type: 'number', default: 20, min: 1, max: 500, step: 1, label: 'Length' },
    },
    description: 'Exponential Moving Average (20 period)',
    aiSynonyms: ['ema 20', 'exponential moving average 20', '지수이동평균 20'],
  },

  ema_26: {
    id: 'ema_26',
    label: 'EMA 26',
    family: 'MovingAverage',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'ema_26',
    category: 'TA',
    paramSchema: {
      length: { type: 'number', default: 26, min: 1, max: 500, step: 1, label: 'Length' },
    },
    description: 'Exponential Moving Average (26 period)',
    aiSynonyms: ['ema 26', 'exponential moving average 26'],
  },

  ema_34: {
    id: 'ema_34',
    label: 'EMA 34',
    family: 'MovingAverage',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'ema_34',
    category: 'TA',
    paramSchema: {
      length: { type: 'number', default: 34, min: 1, max: 500, step: 1, label: 'Length' },
    },
    description: 'Exponential Moving Average (34 period)',
    aiSynonyms: ['ema 34', 'exponential moving average 34'],
  },

  ema_50: {
    id: 'ema_50',
    label: 'EMA 50',
    family: 'MovingAverage',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'ema_50',
    category: 'TA',
    paramSchema: {
      length: { type: 'number', default: 50, min: 1, max: 500, step: 1, label: 'Length' },
    },
    description: 'Exponential Moving Average (50 period)',
    aiSynonyms: ['ema 50', 'exponential moving average 50'],
  },

  ema_100: {
    id: 'ema_100',
    label: 'EMA 100',
    family: 'MovingAverage',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'ema_100',
    category: 'TA',
    paramSchema: {
      length: { type: 'number', default: 100, min: 1, max: 500, step: 1, label: 'Length' },
    },
    description: 'Exponential Moving Average (100 period)',
    aiSynonyms: ['ema 100', 'exponential moving average 100'],
  },

  ema_200: {
    id: 'ema_200',
    label: 'EMA 200',
    family: 'MovingAverage',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'ema_200',
    category: 'TA',
    paramSchema: {
      length: { type: 'number', default: 200, min: 1, max: 500, step: 1, label: 'Length' },
    },
    description: 'Exponential Moving Average (200 period) — long-term trend reference',
    aiSynonyms: ['ema 200', 'exponential moving average 200', '200일 지수이동평균'],
  },

  wma_9: {
    id: 'wma_9',
    label: 'WMA 9',
    family: 'MovingAverage',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'wma_9',
    category: 'TA',
    paramSchema: {
      length: { type: 'number', default: 9, min: 1, max: 500, step: 1, label: 'Length' },
    },
    description: 'Weighted Moving Average (9 period)',
    aiSynonyms: ['wma 9', 'weighted moving average 9', '가중이동평균'],
  },

  wma_20: {
    id: 'wma_20',
    label: 'WMA 20',
    family: 'MovingAverage',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'wma_20',
    category: 'TA',
    paramSchema: {
      length: { type: 'number', default: 20, min: 1, max: 500, step: 1, label: 'Length' },
    },
    description: 'Weighted Moving Average (20 period)',
    aiSynonyms: ['wma 20', 'weighted moving average 20'],
  },

  wma_50: {
    id: 'wma_50',
    label: 'WMA 50',
    family: 'MovingAverage',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'wma_50',
    category: 'TA',
    paramSchema: {
      length: { type: 'number', default: 50, min: 1, max: 500, step: 1, label: 'Length' },
    },
    description: 'Weighted Moving Average (50 period)',
    aiSynonyms: ['wma 50', 'weighted moving average 50'],
  },

  dema_20: {
    id: 'dema_20',
    label: 'DEMA 20',
    family: 'MovingAverage',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'dema_20',
    category: 'TA',
    paramSchema: {
      length: { type: 'number', default: 20, min: 1, max: 500, step: 1, label: 'Length' },
    },
    description: 'Double Exponential Moving Average (20 period) — reduced lag',
    aiSynonyms: ['dema', 'dema 20', 'double exponential moving average'],
  },

  dema_50: {
    id: 'dema_50',
    label: 'DEMA 50',
    family: 'MovingAverage',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'dema_50',
    category: 'TA',
    paramSchema: {
      length: { type: 'number', default: 50, min: 1, max: 500, step: 1, label: 'Length' },
    },
    description: 'Double Exponential Moving Average (50 period)',
    aiSynonyms: ['dema 50', 'double exponential moving average 50'],
  },

  tema_20: {
    id: 'tema_20',
    label: 'TEMA 20',
    family: 'MovingAverage',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'tema_20',
    category: 'TA',
    paramSchema: {
      length: { type: 'number', default: 20, min: 1, max: 500, step: 1, label: 'Length' },
    },
    description: 'Triple Exponential Moving Average (20 period) — very low lag',
    aiSynonyms: ['tema', 'tema 20', 'triple exponential moving average'],
  },

  tema_50: {
    id: 'tema_50',
    label: 'TEMA 50',
    family: 'MovingAverage',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'tema_50',
    category: 'TA',
    paramSchema: {
      length: { type: 'number', default: 50, min: 1, max: 500, step: 1, label: 'Length' },
    },
    description: 'Triple Exponential Moving Average (50 period)',
    aiSynonyms: ['tema 50', 'triple exponential moving average 50'],
  },

  hma_9: {
    id: 'hma_9',
    label: 'HMA 9',
    family: 'MovingAverage',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'hma_9',
    category: 'TA',
    paramSchema: {
      length: { type: 'number', default: 9, min: 1, max: 500, step: 1, label: 'Length' },
    },
    description: 'Hull Moving Average (9 period) — low lag, smooth',
    aiSynonyms: ['hma 9', 'hull moving average 9', '헐이동평균'],
  },

  hma_20: {
    id: 'hma_20',
    label: 'HMA 20',
    family: 'MovingAverage',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'hma_20',
    category: 'TA',
    paramSchema: {
      length: { type: 'number', default: 20, min: 1, max: 500, step: 1, label: 'Length' },
    },
    description: 'Hull Moving Average (20 period)',
    aiSynonyms: ['hma 20', 'hull moving average 20'],
  },

  hma_50: {
    id: 'hma_50',
    label: 'HMA 50',
    family: 'MovingAverage',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'hma_50',
    category: 'TA',
    paramSchema: {
      length: { type: 'number', default: 50, min: 1, max: 500, step: 1, label: 'Length' },
    },
    description: 'Hull Moving Average (50 period)',
    aiSynonyms: ['hma 50', 'hull moving average 50'],
  },

  kama_10: {
    id: 'kama_10',
    label: 'KAMA 10',
    family: 'MovingAverage',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'kama_10',
    category: 'TA',
    paramSchema: {
      length: { type: 'number', default: 10, min: 1, max: 500, step: 1, label: 'Length' },
    },
    description: "Kaufman's Adaptive Moving Average (10 period) — adapts to volatility",
    aiSynonyms: ['kama', 'kama 10', 'kaufman adaptive moving average', '적응형이동평균'],
  },

  kama_20: {
    id: 'kama_20',
    label: 'KAMA 20',
    family: 'MovingAverage',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'kama_20',
    category: 'TA',
    paramSchema: {
      length: { type: 'number', default: 20, min: 1, max: 500, step: 1, label: 'Length' },
    },
    description: "Kaufman's Adaptive Moving Average (20 period)",
    aiSynonyms: ['kama 20', 'kaufman adaptive moving average 20'],
  },

  trima_14: {
    id: 'trima_14',
    label: 'TRIMA 14',
    family: 'MovingAverage',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'trima_14',
    category: 'TA',
    paramSchema: {
      length: { type: 'number', default: 14, min: 1, max: 500, step: 1, label: 'Length' },
    },
    description: 'Triangular Moving Average (14 period) — double-smoothed SMA',
    aiSynonyms: ['trima 14', 'triangular moving average 14'],
  },

  trima_20: {
    id: 'trima_20',
    label: 'TRIMA 20',
    family: 'MovingAverage',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'trima_20',
    category: 'TA',
    paramSchema: {
      length: { type: 'number', default: 20, min: 1, max: 500, step: 1, label: 'Length' },
    },
    description: 'Triangular Moving Average (20 period)',
    aiSynonyms: ['trima', 'trima 20', 'triangular moving average'],
  },

  zlema_20: {
    id: 'zlema_20',
    label: 'ZLEMA 20',
    family: 'MovingAverage',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'zlema_20',
    category: 'TA',
    paramSchema: {
      length: { type: 'number', default: 20, min: 1, max: 500, step: 1, label: 'Length' },
    },
    description: 'Zero-Lag EMA (20 period) — lag-corrected exponential average',
    aiSynonyms: ['zlema', 'zlema 20', 'zero lag ema', 'zero-lag exponential moving average'],
  },

  zlema_50: {
    id: 'zlema_50',
    label: 'ZLEMA 50',
    family: 'MovingAverage',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'zlema_50',
    category: 'TA',
    paramSchema: {
      length: { type: 'number', default: 50, min: 1, max: 500, step: 1, label: 'Length' },
    },
    description: 'Zero-Lag EMA (50 period)',
    aiSynonyms: ['zlema 50', 'zero lag ema 50'],
  },

  alma_20: {
    id: 'alma_20',
    label: 'ALMA 20',
    family: 'MovingAverage',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'alma_20',
    category: 'TA',
    paramSchema: {
      length: { type: 'number', default: 20, min: 1, max: 500, step: 1, label: 'Length' },
    },
    description: 'Arnaud Legoux Moving Average (20 period) — Gaussian-smoothed',
    aiSynonyms: ['alma', 'alma 20', 'arnaud legoux moving average'],
  },

  vwma_20: {
    id: 'vwma_20',
    label: 'VWMA 20',
    family: 'MovingAverage',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'vwma_20',
    category: 'TA',
    paramSchema: {
      length: { type: 'number', default: 20, min: 1, max: 500, step: 1, label: 'Length' },
    },
    description: 'Volume Weighted Moving Average (20 period)',
    aiSynonyms: ['vwma', 'vwma 20', 'volume weighted moving average', '거래량가중이동평균'],
  },

  vwma_50: {
    id: 'vwma_50',
    label: 'VWMA 50',
    family: 'MovingAverage',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'vwma_50',
    category: 'TA',
    paramSchema: {
      length: { type: 'number', default: 50, min: 1, max: 500, step: 1, label: 'Length' },
    },
    description: 'Volume Weighted Moving Average (50 period)',
    aiSynonyms: ['vwma 50', 'volume weighted moving average 50'],
  },

  vwma_100: {
    id: 'vwma_100',
    label: 'VWMA 100',
    family: 'MovingAverage',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'vwma_100',
    category: 'TA',
    paramSchema: {
      length: { type: 'number', default: 100, min: 1, max: 500, step: 1, label: 'Length' },
    },
    description: 'Volume Weighted Moving Average (100 period)',
    aiSynonyms: [
      'vwma 100',
      'vwma100',
      'volume weighted moving average 100',
      '거래량 가중 이동평균 100',
      '거래량가중이동평균 100',
    ],
  },

  // ── Momentum / Oscillators ────────────────────────────────────────────────

  rsi_2: {
    id: 'rsi_2',
    label: 'RSI 2',
    family: 'RelativeStrength',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'rsi_2',
    category: 'TA',
    paramSchema: {
      period: { type: 'number', default: 2, min: 2, max: 100, step: 1, label: 'Period' },
    },
    description: 'RSI (2 period) — extremely short-term oversold/overbought',
    aiSynonyms: ['rsi 2', 'relative strength index 2', '초단기 rsi'],
  },

  rsi_5: {
    id: 'rsi_5',
    label: 'RSI 5',
    family: 'RelativeStrength',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'rsi_5',
    category: 'TA',
    paramSchema: {
      period: { type: 'number', default: 5, min: 2, max: 100, step: 1, label: 'Period' },
    },
    description: 'RSI (5 period) — short-term momentum',
    aiSynonyms: ['rsi 5', 'relative strength index 5'],
  },

  rsi_7: {
    id: 'rsi_7',
    label: 'RSI 7',
    family: 'RelativeStrength',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'rsi_7',
    category: 'TA',
    paramSchema: {
      period: { type: 'number', default: 7, min: 2, max: 100, step: 1, label: 'Period' },
    },
    description: 'RSI (7 period)',
    aiSynonyms: ['rsi 7', 'relative strength index 7'],
  },

  rsi_9: {
    id: 'rsi_9',
    label: 'RSI 9',
    family: 'RelativeStrength',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'rsi_9',
    category: 'TA',
    paramSchema: {
      period: { type: 'number', default: 9, min: 2, max: 100, step: 1, label: 'Period' },
    },
    description: 'RSI (9 period)',
    aiSynonyms: ['rsi 9', 'relative strength index 9'],
  },

  rsi_14: {
    id: 'rsi_14',
    label: 'RSI 14',
    family: 'RelativeStrength',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'rsi_14',
    category: 'TA',
    paramSchema: {
      period: { type: 'number', default: 14, min: 2, max: 100, step: 1, label: 'Period' },
    },
    description: 'RSI (14 period) — standard Wilder period',
    aiSynonyms: ['rsi 14', 'relative strength index 14', '표준 rsi'],
  },

  rsi_21: {
    id: 'rsi_21',
    label: 'RSI 21',
    family: 'RelativeStrength',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'rsi_21',
    category: 'TA',
    paramSchema: {
      period: { type: 'number', default: 21, min: 2, max: 100, step: 1, label: 'Period' },
    },
    description: 'RSI (21 period) — smoothed / slower signal',
    aiSynonyms: ['rsi 21', 'relative strength index 21'],
  },

  macd_12_26_9: {
    id: 'macd_12_26_9',
    label: 'MACD 12/26/9',
    family: 'RelativeStrength',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'macd_12_26_9',
    category: 'TA',
    paramSchema: {
      fast:   { type: 'number', default: 12, min: 2, max: 100, step: 1, label: 'Fast' },
      slow:   { type: 'number', default: 26, min: 2, max: 200, step: 1, label: 'Slow' },
      signal: { type: 'number', default: 9,  min: 2, max: 50,  step: 1, label: 'Signal' },
    },
    description: 'MACD (12/26/9) — standard settings',
    aiSynonyms: ['macd 12 26 9', 'standard macd', '표준 맥디'],
  },

  macd_5_35_5: {
    id: 'macd_5_35_5',
    label: 'MACD 5/35/5',
    family: 'RelativeStrength',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'macd_5_35_5',
    category: 'TA',
    paramSchema: {
      fast:   { type: 'number', default: 5,  min: 2, max: 100, step: 1, label: 'Fast' },
      slow:   { type: 'number', default: 35, min: 2, max: 200, step: 1, label: 'Slow' },
      signal: { type: 'number', default: 5,  min: 2, max: 50,  step: 1, label: 'Signal' },
    },
    description: 'MACD (5/35/5) — slow/weekly variant',
    aiSynonyms: ['macd 5 35 5', 'slow macd'],
  },

  stoch_14_3: {
    id: 'stoch_14_3',
    label: 'Stoch 14/3',
    family: 'RelativeStrength',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'stoch_14_3',
    category: 'TA',
    paramSchema: {
      k: { type: 'number', default: 14, min: 1, max: 100, step: 1, label: 'K Period' },
      d: { type: 'number', default: 3,  min: 1, max: 50,  step: 1, label: 'D Period' },
    },
    description: 'Stochastic Oscillator (14/3) — %K and %D',
    aiSynonyms: ['stochastic', 'stoch', '스토캐스틱', 'stoch 14'],
  },

  stoch_5_3: {
    id: 'stoch_5_3',
    label: 'Stoch 5/3',
    family: 'RelativeStrength',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'stoch_5_3',
    category: 'TA',
    paramSchema: {
      k: { type: 'number', default: 5, min: 1, max: 100, step: 1, label: 'K Period' },
      d: { type: 'number', default: 3, min: 1, max: 50,  step: 1, label: 'D Period' },
    },
    description: 'Stochastic Oscillator (5/3) — faster signal',
    aiSynonyms: ['stoch 5 3', 'fast stochastic'],
  },

  cci_14: {
    id: 'cci_14',
    label: 'CCI 14',
    family: 'RelativeStrength',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'cci_14',
    category: 'TA',
    paramSchema: {
      period: { type: 'number', default: 14, min: 2, max: 200, step: 1, label: 'Period' },
    },
    description: 'Commodity Channel Index (14 period)',
    aiSynonyms: ['cci 14', 'commodity channel index 14'],
  },

  cci_20: {
    id: 'cci_20',
    label: 'CCI 20',
    family: 'RelativeStrength',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'cci_20',
    category: 'TA',
    paramSchema: {
      period: { type: 'number', default: 20, min: 2, max: 200, step: 1, label: 'Period' },
    },
    description: 'Commodity Channel Index (20 period)',
    aiSynonyms: ['cci', 'cci 20', 'commodity channel index', '상품채널지수'],
  },

  mfi_14: {
    id: 'mfi_14',
    label: 'MFI 14',
    family: 'RelativeStrength',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'mfi_14',
    category: 'TA',
    paramSchema: {
      period: { type: 'number', default: 14, min: 2, max: 100, step: 1, label: 'Period' },
    },
    description: 'Money Flow Index (14 period) — volume-weighted RSI',
    aiSynonyms: ['mfi', 'mfi 14', 'money flow index', '머니플로우인덱스'],
  },

  mfi_21: {
    id: 'mfi_21',
    label: 'MFI 21',
    family: 'RelativeStrength',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'mfi_21',
    category: 'TA',
    paramSchema: {
      period: { type: 'number', default: 21, min: 2, max: 100, step: 1, label: 'Period' },
    },
    description: 'Money Flow Index (21 period)',
    aiSynonyms: ['mfi 21', 'money flow index 21'],
  },

  williams_r_14: {
    id: 'williams_r_14',
    label: 'Williams %R 14',
    family: 'RelativeStrength',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'williams_r_14',
    category: 'TA',
    paramSchema: {
      period: { type: 'number', default: 14, min: 2, max: 100, step: 1, label: 'Period' },
    },
    description: "Williams %R (14 period) — overbought/oversold oscillator",
    aiSynonyms: ['williams r', 'williams %r', '윌리엄스 퍼센트r'],
  },

  williams_r_21: {
    id: 'williams_r_21',
    label: 'Williams %R 21',
    family: 'RelativeStrength',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'williams_r_21',
    category: 'TA',
    paramSchema: {
      period: { type: 'number', default: 21, min: 2, max: 100, step: 1, label: 'Period' },
    },
    description: "Williams %R (21 period)",
    aiSynonyms: ['williams r 21', 'williams %r 21'],
  },

  roc_9: {
    id: 'roc_9',
    label: 'ROC 9',
    family: 'RelativeStrength',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'roc_9',
    category: 'TA',
    paramSchema: {
      period: { type: 'number', default: 9, min: 1, max: 200, step: 1, label: 'Period' },
    },
    description: 'Rate of Change (9 period) — % price change',
    aiSynonyms: ['roc 9', 'rate of change 9', '변화율'],
  },

  roc_12: {
    id: 'roc_12',
    label: 'ROC 12',
    family: 'RelativeStrength',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'roc_12',
    category: 'TA',
    paramSchema: {
      period: { type: 'number', default: 12, min: 1, max: 200, step: 1, label: 'Period' },
    },
    description: 'Rate of Change (12 period)',
    aiSynonyms: ['roc', 'roc 12', 'rate of change 12'],
  },

  roc_21: {
    id: 'roc_21',
    label: 'ROC 21',
    family: 'RelativeStrength',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'roc_21',
    category: 'TA',
    paramSchema: {
      period: { type: 'number', default: 21, min: 1, max: 200, step: 1, label: 'Period' },
    },
    description: 'Rate of Change (21 period)',
    aiSynonyms: ['roc 21', 'rate of change 21'],
  },

  momentum_10: {
    id: 'momentum_10',
    label: 'Momentum 10',
    family: 'RelativeStrength',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'momentum_10',
    category: 'TA',
    paramSchema: {
      period: { type: 'number', default: 10, min: 1, max: 200, step: 1, label: 'Period' },
    },
    description: 'Price Momentum (10 period) — absolute price change',
    aiSynonyms: ['momentum', 'momentum 10', '모멘텀'],
  },

  momentum_14: {
    id: 'momentum_14',
    label: 'Momentum 14',
    family: 'RelativeStrength',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'momentum_14',
    category: 'TA',
    paramSchema: {
      period: { type: 'number', default: 14, min: 1, max: 200, step: 1, label: 'Period' },
    },
    description: 'Price Momentum (14 period)',
    aiSynonyms: ['momentum 14', 'price momentum 14'],
  },

  cmo_9: {
    id: 'cmo_9',
    label: 'CMO 9',
    family: 'RelativeStrength',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'cmo_9',
    category: 'TA',
    paramSchema: {
      period: { type: 'number', default: 9, min: 2, max: 100, step: 1, label: 'Period' },
    },
    description: "Chande Momentum Oscillator (9 period)",
    aiSynonyms: ['cmo 9', 'chande momentum oscillator 9'],
  },

  cmo_14: {
    id: 'cmo_14',
    label: 'CMO 14',
    family: 'RelativeStrength',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'cmo_14',
    category: 'TA',
    paramSchema: {
      period: { type: 'number', default: 14, min: 2, max: 100, step: 1, label: 'Period' },
    },
    description: "Chande Momentum Oscillator (14 period)",
    aiSynonyms: ['cmo', 'cmo 14', 'chande momentum oscillator'],
  },

  ppo_12_26: {
    id: 'ppo_12_26',
    label: 'PPO 12/26',
    family: 'RelativeStrength',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'ppo_12_26',
    category: 'TA',
    paramSchema: {
      fast: { type: 'number', default: 12, min: 2, max: 100, step: 1, label: 'Fast' },
      slow: { type: 'number', default: 26, min: 2, max: 200, step: 1, label: 'Slow' },
    },
    description: 'Percentage Price Oscillator (12/26) — MACD as percentage',
    aiSynonyms: ['ppo', 'percentage price oscillator', 'ppo 12 26'],
  },

  trix_14: {
    id: 'trix_14',
    label: 'TRIX 14',
    family: 'RelativeStrength',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'trix_14',
    category: 'TA',
    paramSchema: {
      period: { type: 'number', default: 14, min: 2, max: 100, step: 1, label: 'Period' },
    },
    description: 'TRIX (14 period) — triple-smoothed EMA rate of change',
    aiSynonyms: ['trix 14', 'triple exponential rate of change 14'],
  },

  trix_18: {
    id: 'trix_18',
    label: 'TRIX 18',
    family: 'RelativeStrength',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'trix_18',
    category: 'TA',
    paramSchema: {
      period: { type: 'number', default: 18, min: 2, max: 100, step: 1, label: 'Period' },
    },
    description: 'TRIX (18 period)',
    aiSynonyms: ['trix', 'trix 18', 'triple exponential rate of change'],
  },

  dpo_14: {
    id: 'dpo_14',
    label: 'DPO 14',
    family: 'RelativeStrength',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'dpo_14',
    category: 'TA',
    paramSchema: {
      period: { type: 'number', default: 14, min: 2, max: 200, step: 1, label: 'Period' },
    },
    description: 'Detrended Price Oscillator (14 period) — removes trend to identify cycles',
    aiSynonyms: ['dpo 14', 'detrended price oscillator 14'],
  },

  dpo_20: {
    id: 'dpo_20',
    label: 'DPO 20',
    family: 'RelativeStrength',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'dpo_20',
    category: 'TA',
    paramSchema: {
      period: { type: 'number', default: 20, min: 2, max: 200, step: 1, label: 'Period' },
    },
    description: 'Detrended Price Oscillator (20 period)',
    aiSynonyms: ['dpo', 'dpo 20', 'detrended price oscillator'],
  },

  ultimate_osc: {
    id: 'ultimate_osc',
    label: 'Ult Osc',
    family: 'RelativeStrength',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'ultimate_osc',
    category: 'TA',
    description: 'Ultimate Oscillator — combines 7/14/28 period momentum',
    aiSynonyms: ['ultimate oscillator', 'ult osc', '얼티밋 오실레이터'],
  },

  // ── Trend / Structure ─────────────────────────────────────────────────────

  adx_14: {
    id: 'adx_14',
    label: 'ADX 14',
    family: 'Structure',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'adx_14',
    category: 'TA',
    paramSchema: {
      period: { type: 'number', default: 14, min: 2, max: 100, step: 1, label: 'Period' },
    },
    description: 'Average Directional Index (14 period) — trend strength',
    aiSynonyms: ['adx', 'adx 14', 'average directional index', '추세강도'],
  },

  adx_20: {
    id: 'adx_20',
    label: 'ADX 20',
    family: 'Structure',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'adx_20',
    category: 'TA',
    paramSchema: {
      period: { type: 'number', default: 20, min: 2, max: 100, step: 1, label: 'Period' },
    },
    description: 'Average Directional Index (20 period)',
    aiSynonyms: ['adx 20', 'average directional index 20'],
  },

  aroon_14: {
    id: 'aroon_14',
    label: 'Aroon 14',
    family: 'Structure',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'aroon_14',
    category: 'TA',
    paramSchema: {
      period: { type: 'number', default: 14, min: 2, max: 200, step: 1, label: 'Period' },
    },
    description: 'Aroon Indicator (14 period) — trend direction and strength',
    aiSynonyms: ['aroon', 'aroon 14', '아룬'],
  },

  aroon_25: {
    id: 'aroon_25',
    label: 'Aroon 25',
    family: 'Structure',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'aroon_25',
    category: 'TA',
    paramSchema: {
      period: { type: 'number', default: 25, min: 2, max: 200, step: 1, label: 'Period' },
    },
    description: 'Aroon Indicator (25 period)',
    aiSynonyms: ['aroon 25'],
  },

  psar: {
    id: 'psar',
    label: 'PSAR',
    family: 'Structure',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'psar',
    category: 'TA',
    description: 'Parabolic SAR — stop and reverse trailing stop',
    aiSynonyms: ['psar', 'parabolic sar', 'parabolic stop and reverse', '파라볼릭 sar'],
  },

  psar_fast: {
    id: 'psar_fast',
    label: 'PSAR Fast',
    family: 'Structure',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'psar_fast',
    category: 'TA',
    description: 'Parabolic SAR (fast settings) — higher acceleration factor',
    aiSynonyms: ['psar fast', 'fast parabolic sar'],
  },

  mass_index: {
    id: 'mass_index',
    label: 'Mass Index',
    family: 'Structure',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'mass_index',
    category: 'TA',
    description: 'Mass Index — detects reversal bulges in price range',
    aiSynonyms: ['mass index', '매스 인덱스'],
  },

  chop_14: {
    id: 'chop_14',
    label: 'Chop 14',
    family: 'Structure',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'chop_14',
    category: 'TA',
    paramSchema: {
      period: { type: 'number', default: 14, min: 2, max: 200, step: 1, label: 'Period' },
    },
    description: 'Choppiness Index (14 period) — trending vs choppy market',
    aiSynonyms: ['chop', 'choppiness index', '쵸피니스'],
  },

  chop_20: {
    id: 'chop_20',
    label: 'Chop 20',
    family: 'Structure',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'chop_20',
    category: 'TA',
    paramSchema: {
      period: { type: 'number', default: 20, min: 2, max: 200, step: 1, label: 'Period' },
    },
    description: 'Choppiness Index (20 period)',
    aiSynonyms: ['chop 20', 'choppiness index 20'],
  },

  elder_ray: {
    id: 'elder_ray',
    label: 'Elder Ray',
    family: 'Structure',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'elder_ray',
    category: 'TA',
    description: 'Elder Ray Index — bull and bear power relative to EMA',
    aiSynonyms: ['elder ray', 'elder ray index', '엘더 레이'],
  },

  balance_power: {
    id: 'balance_power',
    label: 'Balance of Power',
    family: 'Structure',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'balance_power',
    category: 'TA',
    description: 'Balance of Power — buyer vs seller strength',
    aiSynonyms: ['balance of power', 'bop', '매수매도 파워'],
  },

  pivot_points: {
    id: 'pivot_points',
    label: 'Pivot Points',
    family: 'Structure',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'pivot_points',
    category: 'TA',
    description: 'Classic Pivot Points — S1/S2/P/R1/R2 support and resistance levels',
    aiSynonyms: ['pivot', 'pivot points', '피봇', '피봇포인트'],
  },

  // ── Volatility ────────────────────────────────────────────────────────────

  atr_5: {
    id: 'atr_5',
    label: 'ATR 5',
    family: 'Volatility',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'atr_5',
    category: 'TA',
    paramSchema: {
      period: { type: 'number', default: 5, min: 1, max: 100, step: 1, label: 'Period' },
    },
    description: 'Average True Range (5 period) — short-term volatility measure',
    aiSynonyms: ['atr 5', 'average true range 5'],
  },

  atr_7: {
    id: 'atr_7',
    label: 'ATR 7',
    family: 'Volatility',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'atr_7',
    category: 'TA',
    paramSchema: {
      period: { type: 'number', default: 7, min: 1, max: 100, step: 1, label: 'Period' },
    },
    description: 'Average True Range (7 period)',
    aiSynonyms: ['atr 7', 'average true range 7'],
  },

  atr_14: {
    id: 'atr_14',
    label: 'ATR 14',
    family: 'Volatility',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'atr_14',
    category: 'TA',
    paramSchema: {
      period: { type: 'number', default: 14, min: 1, max: 100, step: 1, label: 'Period' },
    },
    description: 'Average True Range (14 period) — Wilder standard',
    aiSynonyms: ['atr', 'atr 14', 'average true range', '평균진폭'],
  },

  atr_20: {
    id: 'atr_20',
    label: 'ATR 20',
    family: 'Volatility',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'atr_20',
    category: 'TA',
    paramSchema: {
      period: { type: 'number', default: 20, min: 1, max: 100, step: 1, label: 'Period' },
    },
    description: 'Average True Range (20 period)',
    aiSynonyms: ['atr 20', 'average true range 20'],
  },

  bb_20_2: {
    id: 'bb_20_2',
    label: 'BB 20/2',
    family: 'Volatility',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'bb_20_2',
    category: 'TA',
    paramSchema: {
      period:     { type: 'number', default: 20,  min: 2, max: 200, step: 1,   label: 'Period' },
      multiplier: { type: 'number', default: 2.0, min: 0.5, max: 5, step: 0.5, label: 'Multiplier' },
    },
    description: 'Bollinger Bands (20, 2σ) — standard volatility envelope',
    aiSynonyms: ['bb 20 2', 'bollinger bands 20 2', '볼린저밴드 20 2'],
  },

  bb_20_25: {
    id: 'bb_20_25',
    label: 'BB 20/2.5',
    family: 'Volatility',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'bb_20_25',
    category: 'TA',
    paramSchema: {
      period:     { type: 'number', default: 20,  min: 2, max: 200, step: 1,   label: 'Period' },
      multiplier: { type: 'number', default: 2.5, min: 0.5, max: 5, step: 0.5, label: 'Multiplier' },
    },
    description: 'Bollinger Bands (20, 2.5σ) — wider band for extreme moves',
    aiSynonyms: ['bb 20 2.5', 'bollinger bands 20 2.5'],
  },

  keltner_20_15: {
    id: 'keltner_20_15',
    label: 'Keltner 20/1.5',
    family: 'Volatility',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'keltner_20_15',
    category: 'TA',
    description: 'Keltner Channel (20 period, 1.5× ATR)',
    aiSynonyms: ['keltner', 'keltner channel', '켈트너 채널'],
  },

  keltner_20_2: {
    id: 'keltner_20_2',
    label: 'Keltner 20/2',
    family: 'Volatility',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'keltner_20_2',
    category: 'TA',
    description: 'Keltner Channel (20 period, 2× ATR)',
    aiSynonyms: ['keltner 20 2', 'keltner channel 20 2'],
  },

  donchian_14: {
    id: 'donchian_14',
    label: 'Donchian 14',
    family: 'Volatility',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'donchian_14',
    category: 'TA',
    paramSchema: {
      period: { type: 'number', default: 14, min: 2, max: 200, step: 1, label: 'Period' },
    },
    description: 'Donchian Channel (14 period) — highest high / lowest low channel',
    aiSynonyms: ['donchian', 'donchian 14', 'donchian channel'],
  },

  donchian_20: {
    id: 'donchian_20',
    label: 'Donchian 20',
    family: 'Volatility',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'donchian_20',
    category: 'TA',
    paramSchema: {
      period: { type: 'number', default: 20, min: 2, max: 200, step: 1, label: 'Period' },
    },
    description: 'Donchian Channel (20 period)',
    aiSynonyms: ['donchian 20', 'donchian channel 20', '돈치안 채널'],
  },

  donchian_55: {
    id: 'donchian_55',
    label: 'Donchian 55',
    family: 'Volatility',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'donchian_55',
    category: 'TA',
    paramSchema: {
      period: { type: 'number', default: 55, min: 2, max: 200, step: 1, label: 'Period' },
    },
    description: 'Donchian Channel (55 period) — Turtle Traders breakout channel',
    aiSynonyms: ['donchian 55', 'turtle trader channel', '터틀 채널'],
  },

  // ── Volume indicators ─────────────────────────────────────────────────────

  obv: {
    id: 'obv',
    label: 'OBV',
    family: 'Volume',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'obv',
    category: 'TA',
    description: 'On-Balance Volume — cumulative buy/sell volume',
    aiSynonyms: ['obv', 'on balance volume', '온밸런스볼륨'],
  },

  cmf_20: {
    id: 'cmf_20',
    label: 'CMF 20',
    family: 'Volume',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'cmf_20',
    category: 'TA',
    paramSchema: {
      period: { type: 'number', default: 20, min: 2, max: 100, step: 1, label: 'Period' },
    },
    description: 'Chaikin Money Flow (20 period) — buying/selling pressure',
    aiSynonyms: ['cmf', 'cmf 20', 'chaikin money flow', '차이킨 머니플로우'],
  },

  cmf_21: {
    id: 'cmf_21',
    label: 'CMF 21',
    family: 'Volume',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'cmf_21',
    category: 'TA',
    paramSchema: {
      period: { type: 'number', default: 21, min: 2, max: 100, step: 1, label: 'Period' },
    },
    description: 'Chaikin Money Flow (21 period)',
    aiSynonyms: ['cmf 21', 'chaikin money flow 21'],
  },

  eom_9: {
    id: 'eom_9',
    label: 'EOM 9',
    family: 'Volume',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'eom_9',
    category: 'TA',
    paramSchema: {
      period: { type: 'number', default: 9, min: 2, max: 100, step: 1, label: 'Period' },
    },
    description: 'Ease of Movement (9 period) — price change per unit of volume',
    aiSynonyms: ['eom', 'eom 9', 'ease of movement', '이동 용이성'],
  },

  eom_14: {
    id: 'eom_14',
    label: 'EOM 14',
    family: 'Volume',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'eom_14',
    category: 'TA',
    paramSchema: {
      period: { type: 'number', default: 14, min: 2, max: 100, step: 1, label: 'Period' },
    },
    description: 'Ease of Movement (14 period)',
    aiSynonyms: ['eom 14', 'ease of movement 14'],
  },

  force_index_2: {
    id: 'force_index_2',
    label: 'Force Index 2',
    family: 'Volume',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'force_index_2',
    category: 'TA',
    paramSchema: {
      period: { type: 'number', default: 2, min: 1, max: 100, step: 1, label: 'Period' },
    },
    description: 'Elder Force Index (2 period) — price change × volume',
    aiSynonyms: ['force index 2', 'elder force index 2'],
  },

  force_index_13: {
    id: 'force_index_13',
    label: 'Force Index 13',
    family: 'Volume',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'force_index_13',
    category: 'TA',
    paramSchema: {
      period: { type: 'number', default: 13, min: 1, max: 100, step: 1, label: 'Period' },
    },
    description: 'Elder Force Index (13 period)',
    aiSynonyms: ['force index', 'force index 13', 'elder force index'],
  },

  nvi: {
    id: 'nvi',
    label: 'NVI',
    family: 'Volume',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'nvi',
    category: 'TA',
    description: 'Negative Volume Index — tracks price change on decreasing volume days',
    aiSynonyms: ['nvi', 'negative volume index'],
  },

  pvi: {
    id: 'pvi',
    label: 'PVI',
    family: 'Volume',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'pvi',
    category: 'TA',
    description: 'Positive Volume Index — tracks price change on increasing volume days',
    aiSynonyms: ['pvi', 'positive volume index'],
  },

  volume_sma_20: {
    id: 'volume_sma_20',
    label: 'Vol SMA 20',
    family: 'Volume',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'volume_sma_20',
    category: 'TA',
    paramSchema: {
      period: { type: 'number', default: 20, min: 2, max: 200, step: 1, label: 'Period' },
    },
    description: 'Volume Simple Moving Average (20 period) — volume trend reference',
    aiSynonyms: ['volume sma', 'volume sma 20', '거래량 이동평균'],
  },

  volume_sma_50: {
    id: 'volume_sma_50',
    label: 'Vol SMA 50',
    family: 'Volume',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'volume_sma_50',
    category: 'TA',
    paramSchema: {
      period: { type: 'number', default: 50, min: 2, max: 200, step: 1, label: 'Period' },
    },
    description: 'Volume Simple Moving Average (50 period)',
    aiSynonyms: ['volume sma 50', '거래량 이동평균 50'],
  },

  volume_ema_20: {
    id: 'volume_ema_20',
    label: 'Vol EMA 20',
    family: 'Volume',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'volume_ema_20',
    category: 'TA',
    paramSchema: {
      period: { type: 'number', default: 20, min: 2, max: 200, step: 1, label: 'Period' },
    },
    description: 'Volume Exponential Moving Average (20 period)',
    aiSynonyms: ['volume ema', 'volume ema 20', '거래량 지수이동평균'],
  },

  volume_ema_50: {
    id: 'volume_ema_50',
    label: 'Vol EMA 50',
    family: 'Volume',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'volume_ema_50',
    category: 'TA',
    paramSchema: {
      period: { type: 'number', default: 50, min: 2, max: 200, step: 1, label: 'Period' },
    },
    description: 'Volume Exponential Moving Average (50 period)',
    aiSynonyms: ['volume ema 50', '거래량 지수이동평균 50'],
  },

  volume_rsi_14: {
    id: 'volume_rsi_14',
    label: 'Vol RSI 14',
    family: 'Volume',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'volume_rsi_14',
    category: 'TA',
    paramSchema: {
      period: { type: 'number', default: 14, min: 2, max: 100, step: 1, label: 'Period' },
    },
    description: 'Volume RSI (14 period) — RSI applied to volume series',
    aiSynonyms: ['volume rsi', 'volume rsi 14', '거래량 rsi'],
  },

  // ── Misc / Funding/Basis ──────────────────────────────────────────────────

  funding_sma_8: {
    id: 'funding_sma_8',
    label: 'Funding SMA 8',
    family: 'Funding',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'funding_sma_8',
    category: 'TA',
    paramSchema: {
      period: { type: 'number', default: 8, min: 2, max: 100, step: 1, label: 'Period' },
    },
    description: 'Funding Rate SMA (8 period) — smoothed funding trend',
    aiSynonyms: ['funding sma', 'funding sma 8', '펀딩 이동평균'],
  },

  basis: {
    id: 'basis',
    label: 'Basis',
    family: 'Funding',
    archetype: 'A',
    dimensions: [],
    source: { provider: 'derived' },
    priority: 2,
    defaultVisible: false,
    engineKey: 'basis',
    category: 'TA',
    description: 'Futures basis — spot vs futures price premium/discount',
    aiSynonyms: ['basis', '베이시스', 'futures basis', '선물 베이시스', 'contango', 'backwardation'],
  },
};

// ── Helpers ────────────────────────────────────────────────────────────────

export function byFamily(family: IndicatorFamily): IndicatorDef[] {
  return Object.values(INDICATOR_REGISTRY).filter(d => d.family === family);
}

export function byArchetype(archetype: IndicatorArchetype): IndicatorDef[] {
  return Object.values(INDICATOR_REGISTRY).filter(d => d.archetype === archetype);
}

export function defaultVisible(): IndicatorDef[] {
  return Object.values(INDICATOR_REGISTRY)
    .filter(d => d.defaultVisible)
    .sort((a, b) => a.priority - b.priority);
}

export function getIndicator(id: string): IndicatorDef | undefined {
  return INDICATOR_REGISTRY[id];
}
